'use strict';
// ===================== We Create ERP · reports, statements, GST, TDS, bank, calendar, audit, settings =====================

const reportState = { fy: null, from: '', to: '', asOn: '', ledger: '', detail: false };
let gstMonth = '';
function syncRange() {
    if (reportState.fy !== state.fy) {
        const t = todayISO();
        reportState.fy = state.fy;
        reportState.from = fyStart(state.fy) < co.profile.booksFrom ? co.profile.booksFrom : fyStart(state.fy);
        reportState.to = fyEnd(state.fy) < t ? fyEnd(state.fy) : t;
        reportState.asOn = reportState.to;
    }
}
const rangeCtl = () => `<label class="f">From<input type="date" value="${reportState.from}" onchange="reportState.from=this.value;route()"></label><label class="f">To<input type="date" value="${reportState.to}" onchange="reportState.to=this.value;route()"></label>`;
const asOnCtl = () => `<label class="f">As on<input type="date" value="${reportState.asOn}" onchange="reportState.asOn=this.value;route()"></label>`;
const exportBtns = (id, name) => `<button class="btn btn-s btn-sm" onclick="tableCSV($('#${id}'),'${name}')">${ic('dl')} Excel (CSV)</button><button class="btn btn-s btn-sm" onclick="printReport('${id}','${esc(name)}')">${ic('print')} Print / PDF</button>`;
function printReport(id, title) {
    printHtml(`<div class="inv"><div class="stmt-title"><b>${esc(co.profile.legalName || co.profile.name)}</b><span>${esc(title)}</span></div>${$('#' + id).outerHTML}<p style="font-size:9px;color:#666;margin-top:8px">Generated by We Create ERP on ${new Date().toLocaleString('en-IN')}</p></div>`);
}

const REPORTS = [
    ['Financial statements', [['pl', 'Statement of Profit and Loss', 'Schedule III format, with previous-year figures'], ['bs', 'Balance Sheet', 'Schedule III format, with previous-year figures'], ['cf', 'Cash Flow Statement', 'Indirect method (AS 3 / Ind AS 7)'], ['tb', 'Trial Balance', 'Every ledger, debit and credit']]],
    ['Books', [['daybook', 'Day Book', 'Every voucher in date order'], ['ledger', 'Ledger', 'Any account, customer or vendor'], ['stock', 'Stock summary', 'Quantity and value (weighted average)']]],
    ['Receivables & payables', [['ageing-r', 'Receivables ageing', 'Who owes you, by age'], ['ageing-p', 'Payables ageing', 'Whom you owe, by age'], ['msme', 'MSME dues (45-day rule)', 'For MSME-1 and expense disallowance']]],
    ['Registers', [['salesreg', 'Sales register', 'With GST break-up'], ['purchreg', 'Purchase register', 'With GST, RCM and TDS'], ['hsn', 'HSN summary', 'As needed in GSTR-1 Table 12']]]
];
function viewReports() {
    $('#view').innerHTML = pageHead('Reports & statements', 'Everything is built live from your vouchers. Nothing is typed twice, so the statements always agree with the ledgers and GST returns.')
        + REPORTS.map(([g, list]) => `<div class="card"><h2>${esc(g)}</h2><div class="grid g4">${list.map(([k, t, d]) => `<a class="card co-card" style="text-decoration:none;color:inherit;margin:0" href="#/report/${k}"><b>${esc(t)}</b><div class="note">${esc(d)}</div></a>`).join('')}</div></div>`).join('');
}
function viewReport(key) {
    syncRange();
    const fn = { pl: rptPL, bs: rptBS, cf: rptCF, tb: rptTB, daybook: rptDaybook, ledger: rptLedger, stock: rptStock, 'ageing-r': () => rptAgeing('r'), 'ageing-p': () => rptAgeing('p'), msme: rptMsme, salesreg: () => rptRegister('SI'), purchreg: () => rptRegister('PB'), hsn: rptHsn }[key];
    if (!fn) return go('#/reports');
    fn();
}

// ---------- statement helpers ----------
const prevYear = d => `${Number(d.slice(0, 4)) - 1}${d.slice(4)}`;
function stmtRows(rows, hasPrev) {
    return rows.map(r => {
        if (r.head) return `<tr class="head"><td colspan="${hasPrev ? 4 : 3}">${esc(r.head)}</td></tr>`;
        const cells = `<td class="n">${r.cur == null ? '' : num(r.cur)}</td>${hasPrev ? `<td class="n">${r.prev == null ? '' : num(r.prev)}</td>` : ''}`;
        const main = `<tr class="${r.cls || ''}"><td class="${r.ind || ''}">${esc(r.label)}</td><td class="muted">${esc(r.note || '')}</td>${cells}</tr>`;
        const det = reportState.detail && r.details ? r.details.map(d => `<tr><td class="ind2">${esc(d.name)}</td><td></td><td class="n muted">${num(d.cur)}</td>${hasPrev ? `<td class="n muted">${d.prev == null ? '' : num(d.prev)}</td>` : ''}</tr>`).join('') : '';
        return main + det;
    }).join('');
}
const detailToggle = () => `<label class="chk"><input type="checkbox" ${reportState.detail ? 'checked' : ''} onchange="reportState.detail=this.checked;route()"> Show ledger-wise detail</label>`;
function mergeDetails(cur, prev) {
    const m = new Map();
    (cur || []).forEach(x => m.set(x.l?.name ?? x.name, { name: x.l?.name ?? x.name, cur: x.amt, prev: null }));
    (prev || []).forEach(x => { const k = x.l?.name ?? x.name; const e = m.get(k) || { name: k, cur: 0, prev: 0 }; e.prev = x.amt; m.set(k, e); });
    return [...m.values()];
}
function stmtShell(id, title, subtitle, controls, body, hasPrev, curLabel, prevLabel) {
    $('#view').innerHTML = pageHead(title, subtitle, exportBtns(id, title)) + `<div class="card"><div class="row" style="margin-bottom:14px;align-items:flex-end">${controls}</div>
        <div class="stmt-title"><b>${esc(co.profile.legalName || co.profile.name)}</b><span>${esc(title)} · ${esc(curLabel)}</span></div>
        <div class="tw"><table class="t" id="${id}"><thead><tr><th>Particulars</th><th>Note</th><th class="n">${esc(curLabel)} (₹)</th>${hasPrev ? `<th class="n">${esc(prevLabel)} (₹)</th>` : ''}</tr></thead><tbody>${body}</tbody></table></div>
        <p class="note" style="margin-top:10px">Prepared under Schedule III (Division I) to the Companies Act, 2013 and the Accounting Standards notified under the Companies (Accounting Standards) Rules, 2021. For non-corporate entities the same format is used with "Owner's funds" in place of shareholders' funds.</p></div>`;
}

function rptPL() {
    const { from, to } = reportState;
    const pl = plData(from, to);
    const pf = prevYear(from), pt = prevYear(to);
    const hasPrev = pf >= co.profile.booksFrom || pt >= co.profile.booksFrom && co.vouchers.some(v => v.date <= pt);
    const pp = hasPrev ? plData(pf < co.profile.booksFrom ? co.profile.booksFrom : pf, pt) : null;
    const t = (p, k) => p ? p.tot(p[k]) : null;
    const rows = [
        { label: 'I. Revenue from operations', cur: t(pl, 'revenue'), prev: t(pp, 'revenue'), details: mergeDetails(pl.revenue, pp?.revenue) },
        { label: 'II. Other income', cur: t(pl, 'other'), prev: t(pp, 'other'), details: mergeDetails(pl.other, pp?.other) },
        { label: 'III. Total income (I + II)', cur: pl.totalIncome, prev: pp?.totalIncome, cls: 'sub' },
        { head: 'IV. Expenses' },
        { label: 'Purchases of stock-in-trade', ind: 'ind', cur: t(pl, 'purchases'), prev: t(pp, 'purchases'), details: mergeDetails(pl.purchases, pp?.purchases) },
        { label: 'Changes in inventories of stock-in-trade', ind: 'ind', note: `Opening ${num(pl.openStock)} − closing ${num(pl.closeStock)}`, cur: pl.changeInv, prev: pp?.changeInv },
        { label: 'Employee benefits expense', ind: 'ind', cur: t(pl, 'employee'), prev: t(pp, 'employee'), details: mergeDetails(pl.employee, pp?.employee) },
        { label: 'Finance costs', ind: 'ind', cur: t(pl, 'finance'), prev: t(pp, 'finance'), details: mergeDetails(pl.finance, pp?.finance) },
        { label: 'Depreciation and amortisation expense', ind: 'ind', cur: t(pl, 'dep'), prev: t(pp, 'dep'), details: mergeDetails(pl.dep, pp?.dep) },
        { label: 'Other expenses', ind: 'ind', cur: t(pl, 'otherExp'), prev: t(pp, 'otherExp'), details: mergeDetails(pl.otherExp, pp?.otherExp) },
        { label: 'Total expenses (IV)', cur: pl.totalExp, prev: pp?.totalExp, cls: 'sub' },
        { label: 'V. Profit / (loss) before tax (III − IV)', cur: pl.pbt, prev: pp?.pbt, cls: 'sub' },
        { label: 'VI. Tax expense', cur: t(pl, 'tax'), prev: t(pp, 'tax'), details: mergeDetails(pl.tax, pp?.tax) },
        { label: 'VII. Profit / (loss) for the period (V − VI)', cur: pl.pat, prev: pp?.pat, cls: 'grand' }
    ];
    stmtShell('plT', 'Statement of Profit and Loss', 'Income and expenses for the period, compared with the same period last year. Stock is valued at weighted average cost (AS 2). Tax expense appears once you post the provision for tax as a journal.', rangeCtl() + detailToggle(), stmtRows(rows, hasPrev), hasPrev, `${fmtDate(from)} to ${fmtDate(to)}`, `${fmtDate(pf < co.profile.booksFrom ? co.profile.booksFrom : pf)} to ${fmtDate(pt)}`);
}
function rptBS() {
    const asOn = reportState.asOn;
    const b = bsData(asOn);
    const prevOn = fyEnd(fyOf(asOn) - 1);
    const hasPrev = prevOn >= co.profile.booksFrom;
    const p = hasPrev ? bsData(prevOn) : null;
    const corp = /Ltd/.test(co.profile.entity);
    const line = (label, k, note) => ({ label, ind: 'ind', note, cur: b.tot(k), prev: p ? p.tot(k) : null, details: mergeDetails(b.lines[k], p?.lines[k]) });
    const pay = b.tot('cl_payables'), payP = p ? p.tot('cl_payables') : null;
    const rows = [
        { head: 'I. Equity and liabilities' },
        { label: corp ? '(1) Shareholders\' funds' : '(1) Owner\'s funds', cur: b.equity, prev: p?.equity, cls: 'sub' },
        line(corp ? '(a) Share capital' : '(a) Capital account', 'equity_capital'),
        line('(b) Reserves and surplus', 'equity_reserves'),
        { label: '(2) Non-current liabilities', cur: b.ncl, prev: p?.ncl, cls: 'sub' },
        line('(a) Long-term borrowings', 'ncl_borrow'),
        { label: '(3) Current liabilities', cur: b.cl, prev: p?.cl, cls: 'sub' },
        line('(a) Short-term borrowings', 'cl_borrow'),
        { label: '(b) Trade payables', ind: 'ind', cur: pay, prev: payP, details: mergeDetails(b.lines.cl_payables, p?.lines.cl_payables) },
        { label: '    (A) Dues of micro and small enterprises', ind: 'ind2', cur: Math.min(b.msme, pay), prev: p ? Math.min(p.msme, payP) : null },
        { label: '    (B) Dues of others', ind: 'ind2', cur: r2(pay - Math.min(b.msme, pay)), prev: p ? r2(payP - Math.min(p.msme, payP)) : null },
        line('(c) Other current liabilities', 'cl_other', 'GST, TDS, advances'),
        line('(d) Short-term provisions', 'cl_prov'),
        { label: 'TOTAL', cur: b.totalEL, prev: p?.totalEL, cls: 'grand' },
        { head: 'II. Assets' },
        { label: '(1) Non-current assets', cur: b.nca, prev: p?.nca, cls: 'sub' },
        line('(a) Property, plant and equipment', 'nca_ppe'),
        line('(b) Non-current investments', 'nca_invest'),
        { label: '(2) Current assets', cur: b.ca, prev: p?.ca, cls: 'sub' },
        line('(a) Inventories', 'ca_inventory', 'At weighted average cost'),
        line('(b) Trade receivables', 'ca_receivables'),
        line('(c) Cash and cash equivalents', 'ca_cash'),
        line('(d) Short-term loans and advances', 'ca_loans', 'Incl. TDS receivable'),
        line('(e) Other current assets', 'ca_other', 'Incl. GST input credit'),
        { label: 'TOTAL', cur: b.totalA, prev: p?.totalA, cls: 'grand' }
    ];
    const ok = Math.abs(b.totalEL - b.totalA) < 0.01;
    stmtShell('bsT', 'Balance Sheet', ok ? '✓ Assets equal equity and liabilities.' : `⚠ The balance sheet is out by ${inr(b.totalEL - b.totalA)}. Check opening balances.`, asOnCtl() + detailToggle(), stmtRows(rows, hasPrev), hasPrev, `As at ${fmtDate(asOn)}`, `As at ${fmtDate(prevOn)}`);
}
function rptCF() {
    const { from, to } = reportState;
    const c = cashFlowData(from, to);
    const rows = [
        { head: 'A. Cash flow from operating activities' },
        { label: 'Net profit before tax', ind: 'ind', cur: c.pl.pbt },
        { label: 'Adjustments for: depreciation and amortisation', ind: 'ind', cur: c.depTotal },
        { label: 'Adjustments for: finance costs', ind: 'ind', cur: c.finTotal },
        { label: 'Operating profit before working capital changes', cur: c.opBeforeWc, cls: 'sub' },
        ...c.wc.map(x => ({ label: x.name, ind: 'ind', cur: x.amt })),
        { label: 'Cash generated from operations', cur: c.cashGenerated, cls: 'sub' },
        { label: 'Income tax paid / provided', ind: 'ind', cur: -c.taxTotal },
        { label: 'Net cash from operating activities (A)', cur: c.operating, cls: 'sub' },
        { head: 'B. Cash flow from investing activities' },
        ...c.investing.map(x => ({ label: x.name, ind: 'ind', cur: x.amt })),
        { label: 'Net cash from investing activities (B)', cur: c.inv, cls: 'sub' },
        { head: 'C. Cash flow from financing activities' },
        ...c.financing.map(x => ({ label: x.name, ind: 'ind', cur: x.amt })),
        { label: 'Net cash from financing activities (C)', cur: c.fin, cls: 'sub' },
        { label: 'Net increase / (decrease) in cash (A + B + C)', cur: c.net, cls: 'sub' },
        { label: 'Cash and cash equivalents at the beginning', ind: 'ind', cur: c.openCash },
        { label: 'Cash and cash equivalents at the end', cur: c.closeCash, cls: 'grand' }
    ];
    stmtShell('cfT', 'Cash Flow Statement', Math.abs(c.check) < 0.01 ? '✓ Ties to the movement in cash and bank balances.' : `⚠ Difference of ${inr(c.check)} against cash and bank balances.`, rangeCtl(), stmtRows(rows, false), false, `${fmtDate(from)} to ${fmtDate(to)}`);
}
function rptTB() {
    const asOn = reportState.asOn;
    const rows = allLedgers().map(l => ({ l, b: balance(l.id, asOn) })).filter(x => Math.abs(x.b) > 0.004);
    const os = openingStockValue();
    const groups = {};
    rows.forEach(x => (groups[x.l.group] ||= []).push(x));
    let dr = os, cr = 0;
    const body = Object.entries(GROUPS).filter(([g]) => groups[g]).map(([g, G]) => {
        const list = groups[g];
        const gd = sum(list, x => Math.max(0, x.b)), gc = sum(list, x => Math.max(0, -x.b));
        dr += gd; cr += gc;
        return `<tr class="head"><td>${esc(G.name)}</td><td class="n">${gd ? num(gd) : ''}</td><td class="n">${gc ? num(gc) : ''}</td></tr>` + list.sort((a, b) => a.l.name.localeCompare(b.l.name)).map(x => `<tr class="click" onclick="reportState.ledger='${x.l.id}';go('#/report/ledger')"><td class="ind">${esc(x.l.name)}</td><td class="n">${x.b > 0 ? num(x.b) : ''}</td><td class="n">${x.b < 0 ? num(-x.b) : ''}</td></tr>`).join('');
    }).join('');
    const diff = openingDifference();
    $('#view').innerHTML = pageHead('Trial Balance', 'Closing balance of every ledger. Debits equal credits when the books are complete.', exportBtns('tbT', 'Trial Balance'))
        + `<div class="card"><div class="row" style="margin-bottom:14px;align-items:flex-end">${asOnCtl()}</div><div class="tw"><table class="t" id="tbT"><thead><tr><th>Ledger</th><th class="n">Debit (₹)</th><th class="n">Credit (₹)</th></tr></thead><tbody>
        ${os ? `<tr><td>Opening stock</td><td class="n">${num(os)}</td><td></td></tr>` : ''}${body}
        ${Math.abs(diff) > 0.004 ? `<tr><td>Difference in opening balances</td><td class="n">${diff < 0 ? num(-diff) : ''}</td><td class="n">${diff > 0 ? num(diff) : ''}</td></tr>` : ''}
        </tbody><tfoot><tr><td>Total</td><td class="n">${num(dr + (diff < 0 ? -diff : 0))}</td><td class="n">${num(cr + (diff > 0 ? diff : 0))}</td></tr></tfoot></table></div></div>`;
}
function rptDaybook() {
    const { from, to } = reportState;
    const list = co.vouchers.filter(v => v.date >= from && v.date <= to).sort((a, b) => a.date.localeCompare(b.date) || a.no.localeCompare(b.no));
    $('#view').innerHTML = pageHead('Day Book', 'Every voucher in date order, cancelled ones included (struck through).', exportBtns('dbT', 'Day Book'))
        + `<div class="card"><div class="row" style="margin-bottom:14px;align-items:flex-end">${rangeCtl()}</div><div class="tw"><table class="t" id="dbT"><thead><tr><th>Date</th><th>Voucher</th><th>Type</th><th>Particulars</th><th class="n">Debit</th><th class="n">Credit</th></tr></thead><tbody>
        ${list.map(v => postingsOf(v.status === 'cancelled' ? { ...v, status: 'active' } : v).map((p, i) => `<tr class="${i ? '' : 'click'} ${v.status === 'cancelled' ? 'cancel' : ''}" ${i ? '' : `onclick="go('#/v/${v.id}')"`}><td>${i ? '' : fmtDate(v.date)}</td><td>${i ? '' : esc(v.no)}</td><td>${i ? '' : VTYPES[v.type].short}</td><td class="${i ? 'ind' : ''}">${esc(ledgerOf(p.acc)?.name)}</td>${amtCell(p.dr)}${amtCell(p.cr)}</tr>`).join('')).join('') || '<tr><td colspan="6" class="muted" style="text-align:center;padding:20px">No vouchers in this period.</td></tr>'}
        </tbody></table></div></div>`;
}
function rptLedger() {
    const { from, to } = reportState;
    const id = reportState.ledger || sysId('cash');
    const L = ledgerOf(id);
    const open = from <= co.profile.booksFrom ? L.openDr - L.openCr : balance(id, addDays(from, -1));
    const ents = (book().entries.get(id) || []).filter(e => e.date >= from && e.date <= to);
    let run = open;
    const other = (v, acc) => postingsOf(v).filter(p => p.acc !== acc).map(p => ledgerOf(p.acc)?.name).filter(Boolean).slice(0, 2).join(', ');
    $('#view').innerHTML = pageHead(`Ledger: ${L.name}`, `${GROUPS[L.group].name}`, exportBtns('lgT', `Ledger ${L.name}`))
        + `<div class="card"><div class="row" style="margin-bottom:14px;align-items:flex-end"><label class="f" style="min-width:280px">Ledger<select onchange="reportState.ledger=this.value;route()">${ledgerOptions(id, () => true, '')}</select></label>${rangeCtl()}</div>
        <div class="tw"><table class="t" id="lgT"><thead><tr><th>Date</th><th>Voucher</th><th>Particulars</th><th class="n">Debit</th><th class="n">Credit</th><th class="n">Balance</th></tr></thead><tbody>
        <tr class="sub"><td>${fmtDate(from)}</td><td></td><td>Opening balance</td><td></td><td></td><td class="n">${drcr(open)}</td></tr>
        ${ents.map(e => { const v = vById(e.vid); run += e.dr - e.cr; return `<tr class="click" onclick="go('#/v/${v.id}')"><td>${fmtDate(e.date)}</td><td>${esc(v.no)}</td><td>${esc(other(v, id))}${v.narration ? `<div class="note">${esc(v.narration.slice(0, 60))}</div>` : ''}</td>${amtCell(e.dr)}${amtCell(e.cr)}<td class="n">${drcr(run)}</td></tr>`; }).join('')}
        </tbody><tfoot><tr><td colspan="3">Closing balance · ${fmtDate(to)}</td><td class="n">${num(sum(ents, 'dr'))}</td><td class="n">${num(sum(ents, 'cr'))}</td><td class="n">${drcr(run)}</td></tr></tfoot></table></div>
        ${L.kind === 'contact' && L.ref.email ? '' : ''}</div>`;
}
function rptStock() {
    const s = stockAt(reportState.asOn);
    $('#view').innerHTML = pageHead('Stock summary', 'Quantity on hand and value at weighted average cost (AS 2: lower of cost and net realisable value; check for slow-moving items).', exportBtns('stT', 'Stock summary'))
        + `<div class="card"><div class="row" style="margin-bottom:14px;align-items:flex-end">${asOnCtl()}</div><div class="tw"><table class="t" id="stT"><thead><tr><th>Item</th><th>HSN</th><th class="n">Quantity</th><th class="n">Average cost</th><th class="n">Value</th></tr></thead><tbody>
        ${co.items.filter(i => s.items[i.id]).map(i => { const r = s.items[i.id]; return `<tr><td>${esc(i.name)}</td><td>${esc(i.hsn)}</td><td class="n">${r2(r.qty)} ${esc(i.unit)}${r.qty < 0 ? ' <span class="badge bad">negative</span>' : ''}</td><td class="n">${num(r.avg)}</td><td class="n">${num(r.value)}</td></tr>`; }).join('')}
        </tbody><tfoot><tr><td colspan="4">Total</td><td class="n">${num(s.value)}</td></tr></tfoot></table></div></div>`;
}
function rptAgeing(side) {
    const t = todayISO();
    const type = side === 'r' ? 'SI' : 'PB';
    const buckets = ['Not due', '1–30', '31–60', '61–90', '90+'];
    const rows = {};
    co.vouchers.filter(v => v.type === type && v.status !== 'cancelled').forEach(v => {
        const o = outstanding(v);
        if (o <= 0.009) return;
        const late = daysBetween(dueDate(v), t);
        const b = late <= 0 ? 0 : late <= 30 ? 1 : late <= 60 ? 2 : late <= 90 ? 3 : 4;
        const r = rows[v.partyId] ||= { p: contactById(v.partyId), b: [0, 0, 0, 0, 0], bills: [] };
        r.b[b] += o; r.bills.push({ v, o, late });
    });
    const list = Object.values(rows).sort((a, b) => sum(b.b, x => x) - sum(a.b, x => x));
    const tot = buckets.map((_, i) => sum(list, r => r.b[i]));
    $('#view').innerHTML = pageHead(side === 'r' ? 'Receivables ageing' : 'Payables ageing', 'Open bills by days past the due date (bill date + credit days).', exportBtns('agT', side === 'r' ? 'Receivables ageing' : 'Payables ageing'))
        + `<div class="card"><div class="tw"><table class="t" id="agT"><thead><tr><th>Party</th>${buckets.map(b => `<th class="n">${b}</th>`).join('')}<th class="n">Total</th><th></th></tr></thead><tbody>
        ${list.map(r => `<tr><td><b>${esc(r.p.name)}</b>${r.p.msme ? ' <span class="badge warn">MSME</span>' : ''}<div class="note">${r.bills.map(x => `${x.v.no}: ${num(x.o)}`).join(' · ')}</div></td>${r.b.map(x => amtCell(x)).join('')}<td class="n"><b>${num(sum(r.b, x => x))}</b></td><td>${side === 'r' && r.p.phone ? `<a class="btn btn-s btn-sm" target="_blank" rel="noopener" href="https://wa.me/91${r.p.phone}?text=${encodeURIComponent(fillTemplate('waReminder', { customer: r.p.name, amount: inr(sum(r.b, x => x)), invoices: r.bills.map(x => x.v.no).join(', '), company: co.profile.name, upi: co.profile.upi ? ` by UPI to ${co.profile.upi}` : '' }))}" onclick="return gate('whatsapp')">${ic('msg')} Remind</a>` : ''}</td></tr>`).join('') || '<tr><td colspan="8" class="muted" style="text-align:center;padding:20px">Nothing outstanding.</td></tr>'}
        </tbody><tfoot><tr><td>Total</td>${tot.map(x => amtCell(x)).join('')}<td class="n">${num(sum(tot, x => x))}</td><td></td></tr></tfoot></table></div></div>`;
}
function rptMsme() {
    const t = todayISO();
    const list = co.vouchers.filter(v => v.type === 'PB' && v.status !== 'cancelled' && contactById(v.partyId)?.msme).map(v => {
        const p = contactById(v.partyId);
        const limit = Math.min(45, Number(p.creditDays) || 45);
        return { v, p, o: outstanding(v), due: addDays(v.date, limit), late: daysBetween(addDays(v.date, limit), t) };
    }).filter(x => x.o > 0.009).sort((a, b) => b.late - a.late);
    $('#view').innerHTML = pageHead('MSME dues', 'Under MSMED Act section 15 a buyer must pay a micro or small enterprise within the agreed days, at most 45. Unpaid amounts beyond that are not allowed as an expense until paid, and companies report them in MSME-1.', exportBtns('msT', 'MSME dues'))
        + `<div class="card"><div class="tw"><table class="t" id="msT"><thead><tr><th>Supplier</th><th>Udyam no.</th><th>Bill</th><th>Bill date</th><th>Pay by</th><th class="n">Outstanding</th><th>Status</th></tr></thead><tbody>
        ${list.map(x => `<tr class="click" onclick="go('#/v/${x.v.id}')"><td>${esc(x.p.name)}</td><td>${esc(x.p.udyam || '—')}</td><td>${esc(x.v.no)} (${esc(x.v.refNo)})</td><td>${fmtDate(x.v.date)}</td><td>${fmtDate(x.due)}</td><td class="n">${num(x.o)}</td><td>${x.late > 0 ? `<span class="badge bad">${x.late} days late</span>` : `<span class="badge good">${-x.late} days left</span>`}</td></tr>`).join('') || '<tr><td colspan="7" class="muted" style="text-align:center;padding:20px">No MSME dues.</td></tr>'}
        </tbody><tfoot><tr><td colspan="5">Total · of which past 45 days ${num(sum(list.filter(x => x.late > 0), 'o'))}</td><td class="n">${num(sum(list, 'o'))}</td><td></td></tr></tfoot></table></div></div>`;
}
function rptRegister(type) {
    const { from, to } = reportState;
    const types = type === 'SI' ? ['SI', 'CN'] : ['PB', 'DN'];
    const list = co.vouchers.filter(v => types.includes(v.type) && v.date >= from && v.date <= to).sort((a, b) => a.date.localeCompare(b.date));
    const sg = v => v.status === 'cancelled' ? 0 : (v.type === 'CN' || v.type === 'DN' ? -1 : 1);
    $('#view').innerHTML = pageHead(type === 'SI' ? 'Sales register' : 'Purchase register', 'Notes are shown as negatives. Cancelled documents stay in the list at zero.', exportBtns('rgT', type === 'SI' ? 'Sales register' : 'Purchase register'))
        + `<div class="card"><div class="row" style="margin-bottom:14px;align-items:flex-end">${rangeCtl()}</div><div class="tw"><table class="t" id="rgT"><thead><tr><th>Date</th><th>No.</th>${type === 'PB' ? '<th>Supplier inv.</th>' : ''}<th>Party</th><th>GSTIN</th><th>POS</th><th class="n">Taxable</th><th class="n">CGST</th><th class="n">SGST</th><th class="n">IGST</th><th class="n">Total</th>${type === 'PB' ? '<th class="n">TDS</th><th>RCM</th><th>ITC</th>' : '<th>IRN</th>'}</tr></thead><tbody>
        ${list.map(v => { const s = sg(v), p = contactById(v.partyId); return `<tr class="click ${v.status === 'cancelled' ? 'cancel' : ''}" onclick="go('#/v/${v.id}')"><td>${fmtDate(v.date)}</td><td>${esc(v.no)}</td>${type === 'PB' ? `<td>${esc(v.refNo)}</td>` : ''}<td>${esc(p?.name)}</td><td>${esc(p?.gstin || 'URP')}</td><td>${esc(v.pos)}</td>${amtCell(s * v.totals.taxable)}${amtCell(s * v.totals.cgst)}${amtCell(s * v.totals.sgst)}${amtCell(s * v.totals.igst)}${amtCell(s * v.totals.total)}${type === 'PB' ? `${amtCell(s * (v.tds?.amount || 0))}<td>${v.rcm ? 'Yes' : ''}</td><td>${v.itc === false ? 'No' : 'Yes'}</td>` : `<td>${v.irn ? 'Yes' : ''}</td>`}</tr>`; }).join('')}
        </tbody><tfoot><tr><td colspan="${type === 'PB' ? 6 : 5}">Total</td>${['taxable', 'cgst', 'sgst', 'igst', 'total'].map(k => amtCell(sum(list, v => sg(v) * v.totals[k]))).join('')}${type === 'PB' ? `${amtCell(sum(list, v => sg(v) * (v.tds?.amount || 0)))}<td></td><td></td>` : '<td></td>'}</tr></tfoot></table></div></div>`;
}
function rptHsn() {
    const { from, to } = reportState;
    const m = {};
    co.vouchers.filter(v => ['SI', 'CN'].includes(v.type) && v.status !== 'cancelled' && v.date >= from && v.date <= to).forEach(v => {
        const s = v.type === 'CN' ? -1 : 1;
        v.lines.forEach(l => { const k = `${l.hsn}|${l.effRate}|${l.unit}`; const h = m[k] ||= { hsn: l.hsn, rate: l.effRate, unit: l.unit, b2b: v.kind === 'B2B' || v.kind === 'SEZ', qty: 0, tx: 0, i: 0, c: 0, sg: 0 }; h.qty += s * l.qty; h.tx += s * l.taxable; h.i += s * l.igst; h.c += s * l.cgst; h.sg += s * l.sgst; });
    });
    const list = Object.values(m).sort((a, b) => a.hsn.localeCompare(b.hsn));
    $('#view').innerHTML = pageHead('HSN summary', 'Outward supplies by HSN, rate and unit (GSTR-1 Table 12).', exportBtns('hsT', 'HSN summary'))
        + `<div class="card"><div class="row" style="margin-bottom:14px;align-items:flex-end">${rangeCtl()}</div><div class="tw"><table class="t" id="hsT"><thead><tr><th>HSN/SAC</th><th>UQC</th><th class="n">Rate</th><th class="n">Quantity</th><th class="n">Taxable</th><th class="n">IGST</th><th class="n">CGST</th><th class="n">SGST</th></tr></thead><tbody>
        ${list.map(h => `<tr><td>${esc(h.hsn)}</td><td>${esc(h.unit)}</td><td class="n">${h.rate}%</td><td class="n">${r2(h.qty)}</td>${amtCell(h.tx)}${amtCell(h.i)}${amtCell(h.c)}${amtCell(h.sg)}</tr>`).join('')}
        </tbody></table></div></div>`;
}

// ---------- GST ----------
function viewGst(tab) {
    const months = fyMonths(state.fy).filter(m => m <= ymOf(todayISO()) && lastDay(m) >= co.profile.booksFrom);
    if (!months.includes(gstMonth)) gstMonth = months.at(-1) || ymOf(todayISO());
    const ym = gstMonth;
    const filed = t => co.filings.find(f => f.type === t && (f.period === ym || f.period === `${quarterOf(ym)}-${fyOf(ym + '-01')}`));
    const tabs = [['r1', 'GSTR-1'], ['r3b', 'GSTR-3B'], ['2b', 'GSTR-2B / IMS'], ['ein', 'e-Invoice & e-Way bill'], ['health', 'Pre-filing check']];
    const head = pageHead('GST', `Returns are built from your invoices and bills. ${co.profile.gstin ? `GSTIN ${esc(co.profile.gstin)}` : '<b>Add your GSTIN in Settings.</b>'}`, `<select onchange="gstMonth=this.value;route()">${months.map(m => opt(m, ymLabel(m), ym)).join('')}</select>`)
        + `<div class="tabs">${tabs.map(([k, l]) => `<a href="#/gst/${k}" class="${tab === k ? 'on' : ''} ${k === '2b' ? 'adv' : ''}">${l}</a>`).join('')}</div>`;
    let body = '';
    const sumRow = (label, o) => `<tr><td>${label}</td>${amtCell(o.txval ?? '')}${amtCell(o.iamt)}${amtCell(o.camt)}${amtCell(o.samt)}</tr>`;
    if (tab === 'r1') {
        const g = gstr1(ym);
        const sec = (title, rows) => rows.length ? `<h2 style="margin-top:14px">${title} <span class="badge">${rows.length}</span></h2><div class="tw"><table class="t"><thead><tr><th>No.</th><th>Date</th><th>Party</th><th>GSTIN</th><th>POS</th><th class="n">Value</th><th class="n">Taxable</th><th class="n">Tax</th></tr></thead><tbody>${rows.map(r => `<tr class="click" onclick="go('#/v/${r.v.id}')"><td>${esc(r.v.no)}</td><td>${fmtDate(r.v.date)}</td><td>${esc(r.party?.name)}</td><td>${esc(r.party?.gstin || '')}</td><td>${esc(r.v.pos)}</td><td class="n">${num(r.val)}</td><td class="n">${num(r.v.totals.taxable)}</td><td class="n">${num(r.v.totals.tax)}</td></tr>`).join('')}</tbody></table></div>` : '';
        body = `<div class="card"><div class="row" style="justify-content:space-between"><div>${filed('GSTR-1') ? `<span class="badge good">Filed ${fmtDate(filed('GSTR-1').filedOn)} · ${esc(filed('GSTR-1').ref)}</span> Invoices of this month are locked.` : `<span class="badge warn">Not filed</span> Due ${fmtDate(`${addMonths(ym, 1)}-11`)}`}</div>
            <div class="row"><button class="btn btn-s btn-sm" onclick="if (gate('gstFiling')) download('GSTR1_${co.profile.gstin}_${ym.slice(5)}${ym.slice(0, 4)}.json', JSON.stringify(gstr1Json('${ym}'), null, 1), 'application/json')">${ic('dl')} JSON for GST portal</button>${!filed('GSTR-1') && canEdit() ? `<button class="btn btn-p btn-sm" onclick="fileReturn('GSTR-1','${ym}')">Mark as filed</button>` : ''}</div></div>
            <p class="note" style="margin-top:8px">${g.summary.invoices} invoice(s), ${g.summary.notes} credit note(s), taxable value ${inr(g.summary.taxable)}. Upload the JSON in the GST offline tool or portal and verify before filing.</p>
            ${sec('4A · B2B and SEZ invoices', g.b2b)}${sec('5 · B2C large (inter-state above ₹1 lakh)', g.b2cl)}${sec('6A · Exports', g.exp)}${sec('9B · Credit notes to registered parties', g.cdnr)}${sec('9B · Credit notes to unregistered', g.cdnur)}
            ${g.b2cs.length ? `<h2 style="margin-top:14px">7 · B2C others (summary)</h2><div class="tw"><table class="t"><thead><tr><th>POS</th><th>Type</th><th class="n">Rate</th><th class="n">Taxable</th><th class="n">IGST</th><th class="n">CGST</th><th class="n">SGST</th></tr></thead><tbody>${g.b2cs.map(b => `<tr><td>${esc(stateName(b.pos))}</td><td>${b.sply}</td><td class="n">${b.rt}%</td>${amtCell(b.txval)}${amtCell(b.iamt)}${amtCell(b.camt)}${amtCell(b.samt)}</tr>`).join('')}</tbody></table></div>` : ''}
            ${[['12 · HSN summary – B2B', g.hsnB2B], ['12 · HSN summary – B2C', g.hsnB2C]].map(([t, l]) => l.length ? `<h2 style="margin-top:14px">${t}</h2><div class="tw"><table class="t"><thead><tr><th>HSN</th><th>UQC</th><th class="n">Rate</th><th class="n">Qty</th><th class="n">Taxable</th><th class="n">IGST</th><th class="n">CGST</th><th class="n">SGST</th></tr></thead><tbody>${l.map(h => `<tr><td>${esc(h.hsn)}</td><td>${esc(h.uqc)}</td><td class="n">${h.rt}%</td><td class="n">${r2(h.qty)}</td>${amtCell(h.txval)}${amtCell(h.iamt)}${amtCell(h.camt)}${amtCell(h.samt)}</tr>`).join('')}</tbody></table></div>` : '').join('')}
            ${g.docs.length ? `<h2 style="margin-top:14px">13 · Documents issued</h2><div class="tw"><table class="t"><thead><tr><th>Document</th><th>From</th><th>To</th><th class="n">Total</th><th class="n">Cancelled</th></tr></thead><tbody>${g.docs.map(d => `<tr><td>${d.doc}</td><td>${esc(d.from)}</td><td>${esc(d.to)}</td><td class="n">${d.total}</td><td class="n">${d.cancel}</td></tr>`).join('')}</tbody></table></div>` : ''}</div>`;
    } else if (tab === 'r3b') {
        const g = gstr3b(ym);
        const s = g.setoff;
        body = `<div class="card"><div class="row" style="justify-content:space-between"><div>${filed('GSTR-3B') ? `<span class="badge good">Filed ${fmtDate(filed('GSTR-3B').filedOn)} · ${esc(filed('GSTR-3B').ref)}</span>` : `<span class="badge warn">Not filed</span> Due ${fmtDate(`${addMonths(ym, 1)}-20`)}`}</div>
            <div class="row">${canEdit() ? `<button class="btn btn-s btn-sm" onclick="doSetOff('${ym}')">Post set-off journal</button><button class="btn btn-s btn-sm" onclick="payGst('${ym}')">Pay GST (cash ledger)</button>` : ''}${!filed('GSTR-3B') && canEdit() ? `<button class="btn btn-p btn-sm" onclick="fileReturn('GSTR-3B','${ym}')">Mark as filed</button>` : ''}</div></div>
            <p class="note" style="margin:8px 0">Outward tax liability in GSTR-3B is now auto-filled from GSTR-1 and locked, so GSTR-1 must be right first (correct mistakes through GSTR-1A).</p>
            <h2>3.1 Outward and inward supplies liable to reverse charge</h2><div class="tw"><table class="t"><thead><tr><th>Nature</th><th class="n">Taxable</th><th class="n">IGST</th><th class="n">CGST</th><th class="n">SGST</th></tr></thead><tbody>
            ${sumRow('(a) Outward taxable supplies', g.a)}${sumRow('(b) Zero-rated (export / SEZ)', g.b)}${sumRow('(c) Nil-rated / exempt', g.c)}${sumRow('(d) Inward supplies under reverse charge', g.d)}</tbody></table></div>
            ${g.interUnreg.length ? `<h2 style="margin-top:14px">3.2 Inter-state supplies to unregistered persons</h2><div class="tw"><table class="t"><thead><tr><th>Place of supply</th><th class="n">Taxable</th><th class="n">IGST</th></tr></thead><tbody>${g.interUnreg.map(x => `<tr><td>${esc(stateName(x.pos))}</td>${amtCell(x.txval)}${amtCell(x.iamt)}</tr>`).join('')}</tbody></table></div>` : ''}
            <h2 style="margin-top:14px">4. Eligible ITC</h2><div class="tw"><table class="t"><thead><tr><th>Details</th><th class="n"></th><th class="n">IGST</th><th class="n">CGST</th><th class="n">SGST</th></tr></thead><tbody>
            ${sumRow('A(3) Inward supplies under reverse charge', { ...g.itcRcm, txval: '' })}${sumRow('A(5) All other ITC', { ...g.itcOther, txval: '' })}${sumRow('B(2) Reversed (debit notes / returns)', { ...g.reversal, txval: '' })}${sumRow('Credit brought forward from earlier months', { ...g.carryIn, txval: '' })}${sumRow('C. Net ITC available', { ...g.itcNet, txval: '' })}${sumRow('D. Ineligible ITC (section 17(5))', { ...g.ineligible, txval: '' })}</tbody></table></div>
            <h2 style="margin-top:14px">6.1 Payment of tax</h2><div class="tw"><table class="t"><thead><tr><th></th><th class="n">IGST</th><th class="n">CGST</th><th class="n">SGST</th></tr></thead><tbody>
            <tr><td>Tax payable (other than reverse charge)</td>${amtCell(g.liab.iamt)}${amtCell(g.liab.camt)}${amtCell(g.liab.samt)}</tr>
            <tr><td>Paid through ITC</td>${amtCell(s.use.iamt.iamt + s.use.camt.iamt + s.use.samt.iamt)}${amtCell(s.use.iamt.camt + s.use.camt.camt)}${amtCell(s.use.iamt.samt + s.use.samt.samt)}</tr>
            <tr><td>Reverse charge (cash only)</td>${amtCell(g.rcmLiab.iamt)}${amtCell(g.rcmLiab.camt)}${amtCell(g.rcmLiab.samt)}</tr>
            <tr class="grand"><td>Pay in cash</td>${amtCell(s.cash.iamt)}${amtCell(s.cash.camt)}${amtCell(s.cash.samt)}</tr>
            <tr><td>ITC carried forward</td>${amtCell(s.carry.iamt)}${amtCell(s.carry.camt)}${amtCell(s.carry.samt)}</tr></tbody></table></div>
            <p class="note" style="margin-top:8px">Set-off follows Rule 88A: IGST credit first, then CGST and SGST credit; CGST credit is never used for SGST or the other way round. Credit not used in earlier months is brought forward from the input GST ledgers, so post the set-off journal every month.</p></div>`;
    } else if (tab === '2b' && !hasFeature('recon2b')) {
        body = `<div class="empty"><div style="font-size:28px">🔒</div><b style="display:block;margin:6px 0">GSTR-2B / IMS matching is in the Professional plan</b><p class="note" style="margin-bottom:12px">You are on ${esc(planStatus())}.</p><a class="btn btn-p" href="#/billing">See plans</a></div>`;
    } else if (tab === '2b') {
        const rec = recon2b(ym);
        const cnt = s => rec.filter(x => x.status === s).length;
        body = `<div class="card"><h2>Import GSTR-2B for ${ymLabel(ym)}</h2><div class="row"><input type="file" id="b2file" accept=".json,.csv"><button class="btn btn-p btn-sm" onclick="do2b()">Import & match</button><button class="btn btn-g btn-sm" onclick="download('gstr2b-sample.csv', sample2bCsv('${ym}'), 'text/csv')">Sample CSV</button></div>
            <p class="note" style="margin-top:6px">Download the 2B JSON from the GST portal (Returns → GSTR-2B), or a CSV with GSTIN, invoice no., date, taxable, IGST, CGST, SGST.</p></div>
            <div class="card"><div class="row" style="margin-bottom:10px"><span class="badge good">${cnt('Matched')} matched</span><span class="badge warn">${cnt('Mismatch')} mismatch</span><span class="badge bad">${cnt('Only in books')} only in books</span><span class="badge info">${cnt('Only in 2B')} only in 2B</span></div>
            <div class="tw"><table class="t" id="b2T"><thead><tr><th>Status</th><th>Supplier</th><th>Invoice</th><th class="n">Tax in books</th><th class="n">Tax in 2B</th><th>Note</th><th>IMS action</th></tr></thead><tbody>
            ${rec.map(x => `<tr><td><span class="badge ${{ Matched: 'good', Mismatch: 'warn', 'Only in books': 'bad', 'Only in 2B': 'info' }[x.status]}">${x.status}</span></td><td>${esc(x.v ? contactById(x.v.partyId)?.name : x.r.name || x.r.gstin)}</td><td>${x.v ? `<a href="#/v/${x.v.id}">${esc(x.v.refNo)}</a>` : esc(x.r.inv)}</td><td class="n">${x.bookTax != null ? num(x.bookTax) : '—'}</td><td class="n">${x.portalTax != null ? num(x.portalTax) : '—'}</td><td class="note">${esc(x.note)}</td>
                <td>${x.r ? `<select onchange="setIms('${x.r.id}',this.value)" ${canEdit() ? '' : 'disabled'}>${['Pending', 'Accepted', 'Rejected'].map(s => opt(s, s, x.r.ims)).join('')}</select>` : '—'}</td></tr>`).join('') || '<tr><td colspan="7" class="muted" style="text-align:center;padding:20px">No bills or 2B data for this month.</td></tr>'}
            </tbody></table></div><p class="note" style="margin-top:8px">ITC can be claimed only for invoices that appear in GSTR-2B (section 16(2)(aa)). In IMS, accept what is correct, reject what is not yours or wrong, and keep pending what you will decide later.</p></div>`;
    } else if (tab === 'ein') {
        const list = co.vouchers.filter(v => ['SI', 'CN'].includes(v.type) && ymOf(v.date) === ym && v.status !== 'cancelled');
        const applies = Number(co.profile.aato) > 50000000;
        body = `<div class="card">${applies ? `<p class="note" style="margin-bottom:10px">e-Invoicing applies (turnover above ₹5 crore)${Number(co.profile.aato) >= 100000000 ? '; invoices must be reported within 30 days of their date' : ''}.</p>` : '<p class="note" style="margin-bottom:10px">Your turnover is below ₹5 crore, so e-invoicing does not apply. Change the turnover in Settings if this is wrong.</p>'}
            <div class="tw"><table class="t"><thead><tr><th>Document</th><th>Date</th><th>Party</th><th>Type</th><th class="n">Value</th><th>IRN</th><th>e-Way bill</th><th></th></tr></thead><tbody>
            ${list.map(v => `<tr><td><a href="#/v/${v.id}">${esc(v.no)}</a></td><td>${fmtDate(v.date)}</td><td>${esc(contactById(v.partyId)?.name)}</td><td>${v.kind}</td><td class="n">${num(v.totals.total)}</td><td>${v.irn ? `<span class="badge good">${v.irnTest ? 'TEST ' : ''}IRN</span>` : einvoiceApplies(v) ? `<span class="badge ${daysBetween(v.date, todayISO()) > 20 ? 'bad' : 'warn'}">Pending · day ${daysBetween(v.date, todayISO())}</span>` : '<span class="badge">Not needed</span>'}</td><td>${v.ewb ? `<span class="badge good">${esc(v.ewb.no)}</span>` : ewbNeeded(v) ? '<span class="badge warn">Needed</span>' : '—'}</td><td>${einvoiceApplies(v) && !v.irn && canEdit() ? `<button class="btn btn-s btn-sm" onclick="doIrn('${v.id}')">IRN</button>` : ''}</td></tr>`).join('') || '<tr><td colspan="8" class="muted" style="text-align:center;padding:20px">No invoices this month.</td></tr>'}
            </tbody></table></div><p class="note" style="margin-top:8px">This test build creates the e-invoice JSON in the government schema (INV-01 v1.1) and a TEST IRN. The live version will send them to the IRP through a licensed GSP.</p></div>`;
    } else {
        const H = healthCheck();
        body = `<div class="card">${H.map(h => `<a class="alert ${h.level}" href="${h.route}" style="text-decoration:none;color:inherit"><span class="dot"></span><span class="t">${esc(h.text)}<small>${esc(h.sub)}</small></span></a>`).join('') || '<div class="alert"><span class="dot" style="background:var(--good)"></span><span class="t">Ready to file<small>No problems found.</small></span></div>'}</div>`;
    }
    $('#view').innerHTML = head + body;
}
async function fileReturn(type, ym) {
    if (!gate('gstFiling')) return;
    if (co.profile.gstFreq === 'quarterly') {
        const q = quarterOf(ym);
        if (QUARTERS[q].at(-1) !== Number(ym.slice(5))) return alert(`You file quarterly (QRMP). ${type} for ${q} is filed after the quarter: choose ${ymLabel(`${ym.slice(0, 4)}-${String(QUARTERS[q].at(-1)).padStart(2, '0')}`)}.`);
        ym = `${q}-${fyOf(ym + '-01')}`;
    }
    const ref = await ask({ title: `Mark ${type} for ${/^Q/.test(ym) ? ym : ymLabel(ym)} as filed`, message: 'Enter the ARN from the GST portal. After this, entries in this period cannot be edited or cancelled; corrections go through credit / debit notes or GSTR-1A.', input: 'ARN / acknowledgement', ok: 'Mark filed' });
    if (ref === null) return;
    try { markFiled(type, ym, ref); toast(`${type} marked filed.`); route(); } catch (e) { alert(e.message); }
}
function doSetOff(ym) {
    if (!gate('gstFiling')) return;
    try { const v = postSetOff(ym); toast(`Set-off posted as ${v.no}.`); go(`#/v/${v.id}`); } catch (e) { alert(e.message); }
}
function payGst(ym) {
    if (!gate('gstFiling')) return;
    const g = gstr3b(ym);
    F = null;
    const bank = cashBankAccounts().find(a => a.group === 'bank');
    const k = g.setoff.cash.camt ? 'outCgst' : g.setoff.cash.samt ? 'outSgst' : g.setoff.cash.iamt ? 'outIgst' : g.rcmLiab.iamt || g.rcmLiab.camt ? 'rcmPay' : 'outCgst';
    viewVoucherForm({ type: 'PY', ledgerId: sysId(k), accountId: bank?.id || sysId('cash'), amount: g.setoff.cash[{ outCgst: 'camt', outSgst: 'samt', outIgst: 'iamt' }[k]] || g.setoff.totalCash, narration: `GST paid for ${ymLabel(ym)} (PMT-06 challan). Make one payment per tax head.` });
    history.replaceState(null, '', '#/new/PY');
}
async function do2b() {
    const f = $('#b2file').files[0];
    if (!f) return toast('Choose the 2B file first.');
    try { const r = import2b(await f.text(), f.name.endsWith('.json') ? '' : gstMonth); gstMonth = r.period; toast(`${r.count} invoices imported for ${ymLabel(r.period)}.`); route(); } catch (e) { alert(e.message); }
}
function setIms(id, s) {
    const r = co.gstr2b.find(x => x.id === id);
    audit('IMS action', { entity: 'GST', ref: `${r.gstin} ${r.inv}`, before: r.ims, after: s });
    r.ims = s; saveCo(); toast(`Marked ${s}.`);
}
function sample2bCsv(ym) {
    const rows = activeIn(['PB'], ym).filter(v => !v.rcm && isRegistered(contactById(v.partyId))).map((v, i) => [contactById(v.partyId).gstin, contactById(v.partyId).name, v.refNo, ddmmyyyy(v.date), i === 0 ? v.totals.taxable + 100 : v.totals.taxable, v.totals.igst, v.totals.cgst, v.totals.sgst]);
    return toCSV([['GSTIN of supplier', 'Trade name', 'Invoice number', 'Invoice date', 'Taxable value', 'IGST', 'CGST', 'SGST'], ...rows]);
}

// ---------- TDS ----------
let tdsTab = 'tds', retQ = '', retKind = 'tds';
function viewTds() {
    const fy = state.fy;
    const tabs = [['tds', 'TDS deducted'], ['tcs', 'TCS collected'], ['returns', 'Quarterly returns'], ['codes', 'Payment codes & rates']];
    const head = pageHead('TDS & TCS', `TDS is deducted on purchase bills and TCS collected on sales automatically, by payment code, when the threshold is crossed (Income-tax Act 2025, sections 393 and 394). ${co.profile.tan ? `TAN ${esc(co.profile.tan)}.` : '<b>Add your TAN in Settings → Tax.</b>'}`)
        + `<div class="tabs">${tabs.map(([k, l]) => `<button class="${tdsTab === k ? 'on' : ''}" onclick="tdsTab='${k}';route()">${l}</button>`).join('')}</div>`;
    let body = '';
    if (tdsTab === 'tds' || tdsTab === 'tcs') {
        const kind = tdsTab, K = TAX_KIND[kind], R = taxRegister(kind, fy);
        body = `<div class="card"><h2>Monthly deposit status · FY ${fyLabel(fy)}</h2><div class="tw"><table class="t"><thead><tr><th>Month</th><th class="n">${K.label}</th><th class="n">Deposited</th><th class="n">Pending</th><th>Due by</th><th class="n">Interest (late)</th><th></th></tr></thead><tbody>
            ${R.months.filter(m => m.deducted || m.paid).map(m => `<tr><td>${ymLabel(m.ym)}</td>${amtCell(m.deducted)}${amtCell(m.paid)}${amtCell(m.pending)}<td>${fmtDate(m.due)}${m.paidOn ? ` <span class="badge ${m.paidOn <= m.due ? 'good' : 'warn'}">paid ${fmtDate(m.paidOn)}</span>` : m.pending > 0 && m.due < todayISO() ? ' <span class="badge bad">overdue</span>' : ''}</td>${amtCell(m.interest)}<td>${m.pending > 0.5 && canEdit() ? `<button class="btn btn-s btn-sm" onclick="payTax('${kind}','${m.ym}',${m.pending + m.interest})">Pay</button>` : ''}</td></tr>`).join('') || `<tr><td colspan="7" class="muted" style="text-align:center;padding:20px">No ${K.label} this year.</td></tr>`}
            </tbody></table></div><p class="note" style="margin-top:8px">Deposit by the 7th of the next month (March: 30 April). Late deposit costs interest at 1.5% a month or part of a month from the date of ${kind === 'tds' ? 'deduction' : 'collection'}.</p></div>
            <div class="card"><h2>${kind === 'tds' ? 'Deductions' : 'Collections'}</h2><div class="tw"><table class="t" id="tdT"><thead><tr><th>Date</th><th>${kind === 'tds' ? 'Bill' : 'Invoice'}</th><th>${kind === 'tds' ? 'Deductee' : 'Collectee'}</th><th>PAN</th><th>Payment code</th><th>Nature</th><th class="n">Amount</th><th class="n">Rate</th><th class="n">${K.label}</th></tr></thead><tbody>
            ${R.rows.map(r => `<tr class="click" onclick="go('#/v/${r.v.id}')"><td>${fmtDate(r.v.date)}</td><td>${esc(r.v.no)}</td><td>${esc(r.party.name)}</td><td>${r.party.pan ? esc(r.party.pan) : '<span class="badge bad">No PAN</span>'}</td><td><span class="badge brand">${esc(r.code)}</span> <span class="muted">${esc(K.codes[r.section].old)}</span></td><td>${esc(K.codes[r.section].label)}</td>${amtCell(r.base)}<td class="n">${r.rate}%</td>${amtCell(r.amount)}</tr>`).join('') || '<tr><td colspan="9" class="muted" style="text-align:center;padding:20px">None yet.</td></tr>'}
            </tbody>${R.rows.length ? `<tfoot><tr><td colspan="6">Total</td><td class="n">${num(sum(R.rows, 'base'))}</td><td></td><td class="n">${num(sum(R.rows, 'amount'))}</td></tr></tfoot>` : ''}</table></div></div>`;
    } else if (tdsTab === 'returns') {
        if (!hasFeature('taxReturns')) body = `<div class="empty"><div style="font-size:28px">🔒</div><b style="display:block;margin:6px 0">TDS / TCS return preparation is in the Professional plan</b><p class="note" style="margin-bottom:12px">Deduction, collection and deposit tracking stay free. You are on ${esc(planStatus())}.</p><a class="btn btn-p" href="#/billing">See plans</a></div>`;
        else {
            retQ ||= quarterOf(addMonths(ymOf(todayISO()), -3));
            const ret = taxReturn(retKind, fy, retQ);
            const K = ret.K;
            body = `<div class="card"><div class="row" style="justify-content:space-between;align-items:flex-end"><div class="row">
                <label class="f">Return<select onchange="retKind=this.value;route()">${opt('tds', 'Form 140 — TDS, residents other than salary (old 26Q)', retKind)}${opt('tcs', 'Form 143 — TCS (old 27EQ)', retKind)}</select></label>
                <label class="f">Quarter<select onchange="retQ=this.value;route()">${Object.keys(QUARTERS).map(q => opt(q, `${q} · ${QUARTERS[q].map(m => MONTHS[m - 1]).join('–')}`, retQ)).join('')}</select></label></div>
                <div class="row">${ret.filing ? `<span class="badge good">Filed ${fmtDate(ret.filing.filedOn)} · token ${esc(ret.filing.ref)}</span>` : `<span class="badge ${ret.due < todayISO() ? 'bad' : 'warn'}">Due ${fmtDate(ret.due)}</span>`}</div></div></div>
                <div class="grid g4" style="margin-bottom:16px">
                    <div class="kpi"><div class="v">${ret.rows.length}</div><div class="l">${retKind === 'tds' ? 'Deductee' : 'Collectee'} records</div></div>
                    <div class="kpi"><div class="v">${inr0(ret.total)}</div><div class="l">${K.label} for the quarter</div></div>
                    <div class="kpi" style="--c:${ret.deposited + 0.5 >= ret.total ? 'var(--good)' : 'var(--bad)'}"><div class="v">${inr0(ret.deposited)}</div><div class="l">Deposited in ${ret.challans.length} challan(s)</div></div>
                    <div class="kpi" style="--c:var(--warn)"><div class="v">${inr0(ret.interest + ret.lateFee)}</div><div class="l">Interest + late fee</div><div class="s">Interest ${inr0(ret.interest)} · late fee ${inr0(ret.lateFee)}</div></div></div>
                <div class="card"><h2>Checks before filing</h2>${ret.issues.length ? ret.issues.map(i => `<div class="alert ${i.level}"><span class="dot"></span><span class="t">${esc(i.text)}</span></div>`).join('') : '<div class="alert"><span class="dot" style="background:var(--good)"></span><span class="t">Ready to file<small>Every record has a PAN and every month is fully deposited on time.</small></span></div>'}</div>
                <div class="card"><h2>How to file Form ${K.form}</h2><ol style="margin-left:20px;line-height:1.8;font-size:13.5px">
                    <li>Fix everything in "Checks before filing" above (deposit any shortfall with interest).</li>
                    <li>Download the two files below: ${retKind === 'tds' ? 'deductee' : 'collectee'} details and challan details.</li>
                    <li>Open the free Return Preparation Utility (RPU) from the Protean / TIN-NSDL site, choose Form ${K.form}, enter your TAN details and paste in the rows from the two files.</li>
                    <li>Validate it with the File Validation Utility (FVU) using the CSI file downloaded from the e-filing portal, then upload the FVU file on the income-tax e-filing portal (or at a TIN facilitation centre).</li>
                    <li>Enter the token / PRN number here with "Mark as filed". After TRACES processes it, download certificates in Form ${K.cert} for your ${retKind === 'tds' ? 'deductees' : 'customers'}.</li></ol>
                    <div class="row" style="margin-top:12px"><button class="btn btn-s" onclick="download('Form${K.form}_${retQ}_TY${fyLabel(fy)}_${retKind === 'tds' ? 'deductees' : 'collectees'}.csv','﻿'+taxReturnCsv(taxReturn('${retKind}',${fy},'${retQ}'),'rows'),'text/csv')">${ic('dl')} ${retKind === 'tds' ? 'Deductee' : 'Collectee'} details</button><button class="btn btn-s" onclick="download('Form${K.form}_${retQ}_TY${fyLabel(fy)}_challans.csv','﻿'+taxReturnCsv(taxReturn('${retKind}',${fy},'${retQ}'),'challans'),'text/csv')">${ic('dl')} Challan details</button>${!ret.filing && canEdit() ? `<button class="btn btn-p" onclick="calFile('FORM-${K.form}','${retQ}-${fy}')">Mark as filed</button>` : ''}</div>
                    <p class="note" style="margin-top:10px">Direct upload to the income-tax portal will come with the server version. Returns for January–March 2026 and earlier still use the old Forms 26Q / 27EQ.</p></div>
                <div class="card"><h2>${retKind === 'tds' ? 'Deductee' : 'Collectee'} records</h2><div class="tw"><table class="t"><thead><tr><th>PAN</th><th>Name</th><th>Code</th><th>Date</th><th class="n">Amount</th><th class="n">Rate</th><th class="n">${K.label}</th></tr></thead><tbody>${ret.rows.map(r => `<tr><td>${esc(r.party.pan || 'PANNOTAVBL')}</td><td>${esc(r.party.name)}</td><td>${esc(r.code)}</td><td>${fmtDate(r.v.date)}</td>${amtCell(r.base)}<td class="n">${r.rate}%</td>${amtCell(r.amount)}</tr>`).join('') || '<tr><td colspan="7" class="muted" style="text-align:center;padding:16px">Nothing in this quarter.</td></tr>'}</tbody></table></div></div>`;
        }
    } else {
        const row = (k, s, kind) => `<tr><td><span class="badge brand">${s.code}</span></td><td>${esc(s.old)}</td><td>${esc(s.label)}</td><td class="n">${s.rate}%</td><td>${kind === 'tds' ? (s.single ? `${inr0(s.single)} a bill${s.annual ? ` or ${inr0(s.annual)} a year` : ''}` : s.annual ? `${inr0(s.annual)} a year${s.excess ? ' (on the excess)' : ''}` : 'No threshold') : s.single ? `Sale above ${inr0(s.single)}` : 'From the first rupee'}</td></tr>`;
        body = `<div class="card"><h2>TDS payment codes · section 393</h2><div class="tw"><table class="t"><thead><tr><th>Code</th><th>Old section</th><th>Nature of payment</th><th class="n">Rate</th><th>Threshold</th></tr></thead><tbody>${Object.entries(TDS_SECTIONS).map(([k, s]) => row(k, s, 'tds')).join('')}</tbody></table></div>
            <p class="note" style="margin-top:8px">Without the deductee's PAN, 20% applies (5% for purchase of goods). Salary TDS (section 392, Form 138) is handled in payroll.</p></div>
            <div class="card"><h2>TCS payment codes · section 394</h2><div class="tw"><table class="t"><thead><tr><th>Code</th><th>Old section</th><th>Nature of receipt</th><th class="n">Rate</th><th>Applies</th></tr></thead><tbody>${Object.entries(TCS_SECTIONS).map(([k, s]) => row(k, s, 'tcs')).join('')}</tbody></table></div>
            <p class="note" style="margin-top:8px">Rates for Tax Year 2026-27. TCS is collected on the sale value including GST. Without the buyer's PAN: twice the rate or 5%, whichever is higher. Check the latest CBDT notifications before filing.</p></div>`;
    }
    $('#view').innerHTML = head + body;
}
function payTax(kind, ym, amt) {
    F = null;
    viewVoucherForm({ type: 'PY', ledgerId: sysId(TAX_KIND[kind].ledger), taxMonth: ym, amount: Math.round(amt), accountId: cashBankAccounts().find(a => a.group === 'bank')?.id || sysId('cash'), narration: `${TAX_KIND[kind].label} deposited for ${ymLabel(ym)} (challan ITNS 281, tax year ${fyLabel(fyOf(ym + '-01'))})` });
    history.replaceState(null, '', '#/new/PY');
}
const payTds = (ym, amt) => payTax('tds', ym, amt);

// ---------- bank reconciliation ----------
let bankAcc = '';
function viewBank() {
    if (!hasFeature('bankRecon')) { $('#view').innerHTML = lockedPage('bankRecon'); return; }
    const banks = co.accounts.filter(a => a.group === 'bank');
    if (!banks.length) { $('#view').innerHTML = pageHead('Bank reconciliation', '') + `<div class="empty">Add a bank ledger first (Chart of accounts → New ledger → group "Bank Accounts").</div>`; return; }
    if (!banks.some(b => b.id === bankAcc)) bankAcc = banks[0].id;
    const lines = co.bankLines.filter(l => l.accId === bankAcc).sort((a, b) => a.date.localeCompare(b.date));
    const matchedV = new Set(lines.filter(l => l.vid).map(l => l.vid));
    const first = lines[0]?.date, last = lines.at(-1)?.date;
    const bookEnts = (book().entries.get(bankAcc) || []).filter(e => first && e.date >= first && e.date <= last && !matchedV.has(e.vid));
    const bookBal = last ? balance(bankAcc, last) : balance(bankAcc);
    const notPresented = sum(bookEnts.filter(e => e.cr), 'cr'), notCredited = sum(bookEnts.filter(e => e.dr), 'dr');
    $('#view').innerHTML = pageHead('Bank reconciliation', 'Import the bank statement; entries are matched automatically by amount and date. What is left is either missing from your books (create it in one click) or not yet cleared by the bank.',
        `<select onchange="bankAcc=this.value;route()">${banks.map(b => opt(b.id, b.name, bankAcc)).join('')}</select>`)
        + `<div class="card"><div class="row"><input type="file" id="bkFile" accept=".csv">${canEdit() ? `<button class="btn btn-p btn-sm" onclick="importBank()">Import statement</button><button class="btn btn-s btn-sm" onclick="autoMatch(true)">Auto-match</button>` : ''}<button class="btn btn-g btn-sm" onclick="download('bank-sample.csv', sampleBankCsv(), 'text/csv')">Sample CSV</button></div>
            <p class="note" style="margin-top:6px">CSV columns: Date, Description, Withdrawal (debit), Deposit (credit), Reference. Most Indian bank downloads work as they are.</p></div>
        ${last ? `<div class="card"><h2>Bank reconciliation statement as at ${fmtDate(last)}</h2><div class="tw"><table class="t"><tbody>
            <tr><td>Balance as per books</td><td class="n">${drcr(bookBal)}</td></tr>
            <tr><td>Add: cheques / payments issued but not yet debited by the bank</td><td class="n">${num(notPresented)}</td></tr>
            <tr><td>Less: deposits recorded but not yet credited by the bank</td><td class="n">${num(notCredited)}</td></tr>
            <tr><td>Less: bank entries not yet in the books (net)</td><td class="n">${num(sum(lines.filter(l => !l.vid), l => l.amt))}</td></tr>
            <tr class="grand"><td>Balance as per bank (for the imported period)</td><td class="n">${drcr(bookBal + notPresented - notCredited + sum(lines.filter(l => !l.vid), l => l.amt))}</td></tr></tbody></table></div></div>` : ''}
        <div class="card"><h2>Statement lines <span class="badge good">${lines.filter(l => l.vid).length} matched</span> <span class="badge warn">${lines.filter(l => !l.vid).length} open</span></h2><div class="tw"><table class="t"><thead><tr><th>Date</th><th>Description</th><th class="n">Withdrawal</th><th class="n">Deposit</th><th>Matched with</th><th></th></tr></thead><tbody>
        ${lines.map(l => `<tr><td>${fmtDate(l.date)}</td><td>${esc(l.desc)}</td>${amtCell(l.amt < 0 ? -l.amt : 0)}${amtCell(l.amt > 0 ? l.amt : 0)}<td>${l.vid ? `<a href="#/v/${l.vid}">${esc(vById(l.vid)?.no || '')}</a>` : '<span class="badge warn">Not in books</span>'}</td><td style="white-space:nowrap">${!canEdit() ? '' : l.vid ? `<button class="link" onclick="unmatch('${l.id}')">Unmatch</button>` : `<button class="link" onclick="createFromLine('${l.id}')">Create entry</button>`}</td></tr>`).join('') || '<tr><td colspan="6" class="muted" style="text-align:center;padding:20px">Import a statement to start.</td></tr>'}
        </tbody></table></div></div>
        ${bookEnts.length ? `<div class="card"><h2>In books, not in the statement</h2>${bookEnts.map(e => `<div class="note"><a href="#/v/${e.vid}">${esc(vById(e.vid).no)}</a> · ${fmtDate(e.date)} · ${e.dr ? 'deposit' : 'payment'} ${inr(e.dr || e.cr)}</div>`).join('')}</div>` : ''}`;
}
async function importBank() {
    const f = $('#bkFile').files[0];
    if (!f) return toast('Choose the statement CSV first.');
    try {
        const rows = csvParse(await f.text());
        const head = rows.shift().map(h => h.toLowerCase());
        const col = re => head.findIndex(h => re.test(h));
        const c = { d: col(/date/), n: col(/desc|narration|particular|remark/), w: col(/withdraw|debit|dr/), dp: col(/deposit|credit|cr/), a: col(/^amount/), r: col(/ref|cheque|chq/) };
        if (c.d < 0 || (c.a < 0 && (c.w < 0 || c.dp < 0))) throw new Error('Could not find Date and Withdrawal / Deposit (or Amount) columns.');
        let n = 0;
        rows.forEach(r => {
            const date = anyDateToISO(r[c.d]);
            if (!date) return;
            const amt = c.a >= 0 ? r2(String(r[c.a]).replace(/,/g, '')) : r2(Number(String(r[c.dp] || 0).replace(/,/g, '')) - Number(String(r[c.w] || 0).replace(/,/g, '')));
            if (!amt) return;
            const desc = (r[c.n] || '').trim(), ref = c.r >= 0 ? (r[c.r] || '').trim() : '';
            if (co.bankLines.some(x => x.accId === bankAcc && x.date === date && x.amt === amt && x.desc === desc)) return;   // skip duplicates on re-import
            co.bankLines.push({ id: uid('bl'), accId: bankAcc, date, desc, amt, ref, vid: '' });
            n++;
        });
        audit('Bank statement imported', { entity: 'Bank', ref: accById(bankAcc).name, after: `${n} new lines` });
        saveCo();
        const m = autoMatch(false);
        toast(`${n} lines imported, ${m} matched automatically.`);
        route();
    } catch (e) { alert(e.message); }
}
function autoMatch(show) {
    const used = new Set(co.bankLines.filter(l => l.vid).map(l => l.vid));
    const ents = book().entries.get(bankAcc) || [];
    let n = 0;
    co.bankLines.filter(l => l.accId === bankAcc && !l.vid).forEach(l => {
        const cand = ents.filter(e => !used.has(e.vid) && r2(e.dr - e.cr) === l.amt && Math.abs(daysBetween(e.date, l.date)) <= 5)
            .sort((a, b) => Math.abs(daysBetween(a.date, l.date)) - Math.abs(daysBetween(b.date, l.date)));
        if (cand[0]) { l.vid = cand[0].vid; used.add(cand[0].vid); n++; }
    });
    if (n) { audit('Bank lines auto-matched', { entity: 'Bank', ref: accById(bankAcc).name, after: `${n} matched` }); saveCo(); }
    if (show) { toast(`${n} line(s) matched.`); route(); }
    return n;
}
function unmatch(id) { const l = co.bankLines.find(x => x.id === id); l.vid = ''; audit('Bank line unmatched', { entity: 'Bank', ref: l.desc }); saveCo(); route(); }
function createFromLine(id) {
    const l = co.bankLines.find(x => x.id === id);
    const guess = co.contacts.find(c => l.desc.toLowerCase().includes(c.name.toLowerCase().split(' ')[0])) || null;
    const rule = co.rules.find(r => l.desc.toLowerCase().includes(r.word));
    modal({
        title: `${l.amt > 0 ? 'Receipt' : 'Payment'} from bank line`,
        body: `<p class="note" style="margin-bottom:10px">${fmtDate(l.date)} · ${esc(l.desc)} · <b>${inr(Math.abs(l.amt))}</b></p><div id="clErr"></div>
            <label class="f">${l.amt > 0 ? 'Received from' : 'Paid to'}<select id="cl_who">${ledgerOptions(guess?.id || rule?.acc || '', x => !['bank', 'cash'].includes(x.group))}</select></label>
            <label class="chk" style="margin-top:10px"><input type="checkbox" id="cl_rule"> Remember: lines containing "<input id="cl_word" style="width:140px;padding:3px 6px" value="${esc(l.desc.split(/\s+/)[0] || '')}">" go to this ledger</label>`,
        foot: `<button class="btn btn-s" onclick="closeModal()">Cancel</button><button class="btn btn-p" id="clOk">Create & match</button>`,
        onOpen: () => $('#clOk').onclick = () => {
            const who = ledgerOf(val('cl_who'));
            if (!who) return showErr('#clErr', 'Choose the ledger.');
            try {
                const v = saveVoucher({ type: l.amt > 0 ? 'RC' : 'PY', date: l.date, accountId: l.accId, partyId: who.kind === 'contact' ? who.id : '', ledgerId: who.kind === 'account' ? who.id : '', amount: Math.abs(l.amt), refNo: l.ref, narration: l.desc }, { source: 'Bank statement' });
                if (who.kind === 'contact') { const bills = openBills(who.id, l.amt > 0 ? 'SI' : 'PB'); let left = Math.abs(l.amt); v.alloc = []; bills.forEach(b => { if (left <= 0) return; const a = r2(Math.min(left, b.due)); v.alloc.push({ vid: b.v.id, amt: a }); left = r2(left - a); }); }
                l.vid = v.id;
                if (chk('cl_rule') && val('cl_word')) co.rules.push({ word: val('cl_word').toLowerCase(), acc: who.id });
                saveCo(); closeModal(); toast(`${v.no} created and matched.`); route();
            } catch (e) { showErr('#clErr', e); }
        }
    });
}
function sampleBankCsv() {
    const ents = (book().entries.get(bankAcc) || []).slice(-8);
    const rows = ents.map(e => [ddmmyyyy(e.date, '/'), (vById(e.vid).narration || ledgerOf(vById(e.vid).partyId || vById(e.vid).ledgerId)?.name || 'Transfer').slice(0, 40), e.cr ? e.cr : '', e.dr ? e.dr : '', vById(e.vid).refNo || '']);
    rows.push([ddmmyyyy(todayISO(), '/'), 'BANK CHARGES SMS ALERT', 59, '', '']);
    rows.push([ddmmyyyy(todayISO(), '/'), 'INT CREDIT SAVINGS', '', 412, '']);
    return toCSV([['Date', 'Description', 'Withdrawal', 'Deposit', 'Reference'], ...rows]);
}

// ---------- compliance calendar ----------
function viewCalendar() {
    const items = complianceItems(state.fy).filter(i => i.due >= co.profile.booksFrom);
    const badge = { filed: 'good', overdue: 'bad', soon: 'warn', upcoming: 'info' };
    $('#view').innerHTML = pageHead('Due dates', `Every statutory filing for FY ${fyLabel(state.fy)} with its due date and status. Dates follow the Acts; check the portals for extensions announced by CBDT / CBIC.`)
        + `<div class="card"><div class="tw"><table class="t" id="calT"><thead><tr><th>Due date</th><th>Filing</th><th>Law</th><th>Status</th><th></th></tr></thead><tbody>
        ${items.map(i => `<tr><td>${fmtDate(i.due)}</td><td>${esc(i.label)}</td><td class="note">${esc(i.law)}</td><td><span class="badge ${badge[i.state]}">${i.filed ? `Filed ${fmtDate(i.filed.filedOn)}${i.filed.ref ? ' · ' + esc(i.filed.ref) : ''}` : i.state === 'overdue' ? `Overdue ${daysBetween(i.due, todayISO())}d` : i.state === 'soon' ? `Due in ${daysBetween(todayISO(), i.due)}d` : 'Upcoming'}</span></td>
            <td>${!i.filed && canEdit() ? `<button class="link" onclick="${['GSTR-1', 'GSTR-3B'].includes(i.type) ? `gstMonth='${/^Q/.test(i.period) ? i.due.slice(0, 7) && addMonths(i.due.slice(0, 7), -1) : i.period}';go('#/gst/${i.type === 'GSTR-1' ? 'r1' : 'r3b'}')` : `calFile('${i.type}','${i.period}')`}">${['GSTR-1', 'GSTR-3B'].includes(i.type) ? 'Prepare' : 'Mark filed'}</button>` : ''}</td></tr>`).join('')}
        </tbody></table></div></div>`;
}
async function calFile(type, period) {
    const ref = await ask({ title: 'Mark as filed', message: 'Enter the acknowledgement / challan reference.', input: 'Reference', ok: 'Mark filed' });
    if (ref === null) return;
    try { markFiled(type, period, ref); route(); } catch (e) { alert(e.message); }
}

// ---------- audit trail ----------
let auditQ = '', auditSys = false;
function viewAudit() {
    const chain = auditSys ? meta.audit : co.audit;
    const ok = verifyChain(chain);
    const list = chain.slice().reverse().filter(a => !auditQ || JSON.stringify(a).toLowerCase().includes(auditQ.toLowerCase()));
    $('#view').innerHTML = pageHead('Audit trail', 'Every change with date, time, user, old and new values and reason. It is always on and cannot be switched off or edited (Companies (Accounts) Rules 2014, Rule 3(1)). Each entry is sealed with a SHA-256 hash of the one before, so any tampering breaks the chain.',
        `<button class="btn btn-s btn-sm" onclick="tableCSV($('#auT'),'audit-trail')">${ic('dl')} Export</button>`)
        + `<div class="card"><div class="row" style="justify-content:space-between"><div class="row"><input placeholder="Search user, voucher, action" value="${esc(auditQ)}" onchange="auditQ=this.value;route()" style="min-width:260px"><label class="chk"><input type="checkbox" ${auditSys ? 'checked' : ''} onchange="auditSys=this.checked;route()"> Sign-ins & users (workspace log)</label></div>
            <span class="badge ${ok.ok ? 'good' : 'bad'}" style="font-size:13px">${ok.ok ? `✓ Chain intact · ${ok.count} entries` : `✗ Tampering detected at entry ${ok.at}`}</span></div>
        <div class="tw" style="margin-top:12px"><table class="t" id="auT"><thead><tr><th>#</th><th>When</th><th>User</th><th>Action</th><th>Reference</th><th>Before</th><th>After</th><th>Reason</th></tr></thead><tbody>
        ${list.slice(0, 500).map(a => `<tr><td>${a.seq}</td><td style="white-space:nowrap">${new Date(a.at).toLocaleString('en-IN')}</td><td>${esc(a.user)}<div class="note">${esc(ROLES[a.role] || '')}</div></td><td><b>${esc(a.action)}</b></td><td>${esc(a.ref)}</td><td class="note" style="max-width:240px">${esc(a.before)}</td><td class="note" style="max-width:320px">${esc(a.after)}</td><td class="note">${esc(a.reason)}</td></tr>`).join('')}
        </tbody></table></div>${list.length > 500 ? '<p class="note">Showing the latest 500. Export for all.</p>' : ''}</div>`;
}

// ---------- settings ----------
function viewSettings(tab) {
    const tabs = [['company', 'Company'], ['invoice', 'Invoice & print'], ['tax', 'GST & TDS'], ['prefs', 'Preferences'], ['reminders', 'Reminders'], ['import', 'Import'], ['numbering', 'Numbering & lock'], ['users', 'Users & roles'], ['backup', 'Backup & restore']];
    const p = co.profile, P = co.settings.prefs ||= {};
    const ro = isAdmin() ? '' : 'disabled';
    const fld = (key, label, hint = '', type = 'text', extra = '') => `<label class="f">${label}${hint ? ` <span class="hint">${hint}</span>` : ''}<input type="${type}" value="${esc(p[key] ?? '')}" ${ro} ${extra} onchange="setProfile('${key}', this.value)"></label>`;
    const sel = (key, label, opts, hint = '') => `<label class="f">${label}${hint ? ` <span class="hint">${hint}</span>` : ''}<select ${ro} onchange="setProfile('${key}', this.value)">${opts.map(([v, l]) => opt(v, l, p[key] ?? opts[0][0])).join('')}</select></label>`;
    const pref = (key, label, hint, type = 'number', dflt = '') => `<label class="f">${label}${hint ? ` <span class="hint">${hint}</span>` : ''}<input type="${type}" value="${esc(P[key] ?? dflt)}" ${ro} onchange="setPref('${key}', this.value)"></label>`;
    const prefChk = (key, label, dflt = false) => `<label class="chk"><input type="checkbox" ${(P[key] ?? dflt) ? 'checked' : ''} ${ro} onchange="setPref('${key}', this.checked)"> ${label}</label>`;
    let body = '';
    if (tab === 'company') {
        const p = co.profile;
        body = `<div class="card"><div class="row" style="justify-content:space-between"><h2>${esc(p.name)}</h2>${isAdmin() ? '<button class="btn btn-p btn-sm" onclick="companyForm(true)">Edit details</button>' : ''}</div>
            <dl class="found">${[['Legal name', p.legalName], ['Entity', p.entity], ['GSTIN', p.gstin], ['PAN', p.pan], ['TAN', p.tan], ['State', stateName(p.state)], ['Address', `${p.address} ${p.city} ${p.pincode}`], ['Books from', fmtDate(p.booksFrom)], ['Last year turnover', inr0(p.aato || 0)], ['LUT for exports', p.lut ? 'Yes' : 'No'], ['Bank on invoices', `${p.bankName} ${p.bankAcc} ${p.bankIfsc}`]].map(([k, v]) => `<dt>${k}</dt><dd>${esc(v || '—')}</dd>`).join('')}</dl></div>`;
    } else if (tab === 'invoice') {
        const design = hasFeature('invoiceDesign');
        body = `<div class="card"><h2>Logo, signature and UPI ${design ? '' : '<span class="badge warn">Standard plan</span>'}</h2>
            <div class="grid g3"><div><p class="note" style="margin-bottom:8px">Logo (printed top-left)</p>${p.logo ? `<img src="${p.logo}" alt="" style="height:64px;border:1px solid var(--line);border-radius:8px">` : '<div class="note">No logo</div>'}<div class="row" style="margin-top:8px"><button class="btn btn-s btn-sm" ${ro} onclick="if (gate('invoiceDesign')) pickImage('logo')">${p.logo ? 'Replace' : 'Upload'}</button>${p.logo ? `<button class="link" ${ro} onclick="setProfile('logo','')">Remove</button>` : ''}</div></div>
            <div><p class="note" style="margin-bottom:8px">Signature (above "Authorised signatory")</p>${p.signature ? `<img src="${p.signature}" alt="" style="height:48px;border:1px solid var(--line);border-radius:8px;background:#fff">` : '<div class="note">No signature</div>'}<div class="row" style="margin-top:8px"><button class="btn btn-s btn-sm" ${ro} onclick="if (gate('invoiceDesign')) pickImage('signature')">${p.signature ? 'Replace' : 'Upload'}</button>${p.signature ? `<button class="link" ${ro} onclick="setProfile('signature','')">Remove</button>` : ''}</div></div>
            <div>${fld('upi', 'UPI ID for payment QR', 'e.g. kaveri@hdfcbank', 'text', design ? '' : 'disabled')}<p class="note" style="margin-top:6px">Printed invoices show a QR the customer scans to pay the exact amount due.</p></div></div></div>
            <div class="card"><h2>Text on invoices</h2><div class="fg">${fld('terms', 'Terms & conditions')}${fld('invoiceNote', 'Note at the bottom', 'e.g. Thank you for your business')}${fld('jurisdiction', 'Jurisdiction line', 'e.g. Subject to Chennai jurisdiction')}
                ${sel('showBank', 'Show bank details on invoices', [['yes', 'Yes'], ['no', 'No']])}${sel('copies', 'Copy label', [['original', 'Original for recipient'], ['triplicate', 'Original / Duplicate / Triplicate']])}</div></div>`;
    } else if (tab === 'tax') {
        body = `<div class="card"><h2>GST</h2><div class="fg">
            ${sel('gstType', 'Registration type', [['regular', 'Regular'], ['composition', 'Composition scheme (no tax on sales, no input credit)']])}
            ${sel('gstFreq', 'Return filing', [['monthly', 'Monthly GSTR-1 and GSTR-3B'], ['quarterly', 'Quarterly — QRMP scheme (turnover up to ₹5 crore)']])}
            ${fld('aato', 'Last year turnover (₹)', 'Above ₹5 crore: e-invoicing; ₹10 crore+: 30-day reporting limit', 'number')}
            ${fld('lutNo', 'LUT reference (ARN)', 'For exports / SEZ without IGST')}${fld('lutTill', 'LUT valid till', '', 'date')}
            </div><p class="note" style="margin-top:10px">${p.gstType === 'composition' ? 'Composition: sales print as "Bill of Supply" with no GST, and purchases carry no input credit. File CMP-08 quarterly and GSTR-4 yearly.' : 'Regular: tax invoices with GST; input credit on eligible purchases.'}</p></div>
            <div class="card"><h2>TDS / TCS (deductor details for returns)</h2><div class="fg">
            ${fld('tan', 'TAN', 'e.g. CHEA12345B', 'text', 'maxlength="10" style="text-transform:uppercase"')}
            ${sel('deductorType', 'Type of deductor', [['company', 'Company'], ['firm', 'Firm / LLP'], ['individual', 'Individual / HUF (audited)'], ['aop', 'AOP / BOI / Trust'], ['govt', 'Government']])}
            ${fld('respName', 'Person responsible — name')}${fld('respDesig', 'Designation')}${fld('respPan', 'PAN', '', 'text', 'maxlength="10" style="text-transform:uppercase"')}${fld('respMobile', 'Mobile', '', 'tel', 'maxlength="10"')}
            </div><p class="note" style="margin-top:10px">These details are printed on Forms 140 and 143 and on the certificates.</p></div>`;
    } else if (tab === 'prefs') {
        body = `<div class="card"><h2>Defaults for new records</h2><div class="fg">${pref('custDays', 'Credit days for new customers', '', 'number', 30)}${pref('vendDays', 'Credit days for new vendors', '', 'number', 30)}${pref('defaultGst', 'Default GST rate for new items (%)', '', 'number', 18)}</div></div>
            <div class="card"><h2>Alerts</h2><div class="grid g2">${prefChk('warnNegStock', 'Warn when a sale makes stock negative', true)}${prefChk('warnLargeJv', 'Ask for confirmation on journals above the limit below', true)}${pref('largeJv', 'Large journal limit (₹)', '', 'number', 500000)}${prefChk('warnDuplicateSale', 'Warn on a second invoice to the same customer for the same amount on the same day', true)}</div></div>
            <div class="card"><h2>Security</h2><div class="fg">${pref('idleMinutes', 'Sign out after inactivity (minutes)', '5 to 240', 'number', 30)}</div></div>`;
    } else if (tab === 'reminders') {
        const tpl = (key, label, dflt) => `<label class="f wide">${label}<textarea rows="3" ${ro} onchange="setPref('${key}', this.value)">${esc(P[key] ?? dflt)}</textarea></label>`;
        body = `<div class="card"><h2>WhatsApp messages ${hasFeature('whatsapp') ? '' : '<span class="badge warn">Standard plan</span>'}</h2><p class="note" style="margin-bottom:10px">Placeholders: {customer} {amount} {invoices} {due} {company} {upi}</p><div class="fg">
            ${tpl('waReminder', 'Payment reminder', REMINDER_DEFAULTS.waReminder)}${tpl('waInvoice', 'Sending an invoice', REMINDER_DEFAULTS.waInvoice)}${tpl('waReceipt', 'Thank-you for a payment', REMINDER_DEFAULTS.waReceipt)}
            ${pref('remindAfter', 'Show "Remind" for invoices overdue by (days)', '', 'number', 1)}</div></div>`;
    } else if (tab === 'import') {
        body = `<div class="card"><h2>Import from Excel / CSV ${hasFeature('import') ? '' : '<span class="badge warn">Standard plan</span>'}</h2><p class="note" style="margin-bottom:12px">Save your sheet as CSV with the columns in the template. GSTINs and PANs are checked; rows with errors are listed and skipped.</p>
            <div class="grid g3">${['customers', 'vendors', 'items'].map(k => `<div class="card" style="margin:0"><b style="text-transform:capitalize">${k}</b><div class="row" style="margin-top:10px"><button class="btn btn-g btn-sm" onclick="download('${k}-template.csv', importTemplate('${k}'), 'text/csv')">Template</button></div><input type="file" accept=".csv" id="imp_${k}" style="margin-top:10px;width:100%"><button class="btn btn-p btn-sm" style="margin-top:8px" ${canEdit() ? '' : 'disabled'} onclick="if (gate('import')) runImport('${k}')">Import</button></div>`).join('')}</div><div id="impOut" style="margin-top:14px"></div></div>`;
    } else if (tab === 'numbering') {
        body = `<div class="card"><h2>Voucher number prefixes</h2><p class="note" style="margin-bottom:10px">Numbers run per financial year: PREFIX/26-27/0001. GST allows up to 16 characters, using letters, digits, "/" and "-".</p><div class="fg">${Object.entries(VTYPES).map(([k, t]) => `<label class="f">${t.name}<input id="px_${k}" maxlength="6" value="${esc(co.settings.prefixes[k] || t.prefix)}" ${isAdmin() ? '' : 'readonly'}></label>`).join('')}</div>${isAdmin() ? '<button class="btn btn-p btn-sm" style="margin-top:12px" onclick="savePrefixes()">Save prefixes</button>' : ''}</div>
            <div class="card"><h2>Lock the books</h2><p class="note" style="margin-bottom:10px">After you close a period (for example once the auditor signs off), lock it so no entry on or before that date can be added, changed or cancelled.</p><div class="row"><input type="date" id="lockDate" value="${esc(co.settings.lockDate)}" ${isAdmin() ? '' : 'disabled'}>${isAdmin() ? '<button class="btn btn-p btn-sm" onclick="saveLock()">Save lock date</button>' : ''}</div><p class="note" style="margin-top:6px">${co.settings.lockDate ? `Locked up to ${fmtDate(co.settings.lockDate)}.` : 'Nothing is locked.'}</p></div>`;
    } else if (tab === 'users') {
        body = `<div class="card"><div class="row" style="justify-content:space-between"><h2>Users</h2>${isAdmin() ? '<button class="btn btn-p btn-sm" onclick="userForm()">+ Add user</button>' : ''}</div>
            <div class="tw"><table class="t"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Companies</th><th>Status</th><th>Last sign-in</th><th></th></tr></thead><tbody>
            ${meta.users.map(u => `<tr><td>${esc(u.name)}${u.id === me.id ? ' <span class="badge brand">You</span>' : ''}</td><td>${esc(u.username)}</td><td>${ROLES[u.role]}</td><td>${u.companies === 'all' ? 'All' : (u.companies || []).map(id => esc(meta.companies.find(c => c.id === id)?.name || '')).join(', ')}</td><td>${u.active !== false ? '<span class="badge good">Active</span>' : '<span class="badge">Disabled</span>'}</td><td>${u.lastLogin ? new Date(u.lastLogin).toLocaleString('en-IN') : '—'}</td><td>${isAdmin() ? `<button class="link" onclick="userForm('${u.id}')">Edit</button>` : ''}</td></tr>`).join('')}
            </tbody></table></div>
            <table class="t" style="margin-top:14px"><thead><tr><th>What each role can do</th><th>Owner / Admin</th><th>Accountant</th><th>Auditor</th></tr></thead><tbody>${[['Enter, edit and cancel vouchers', 1, 1, 0], ['Masters, GST, TDS, bank reconciliation', 1, 1, 0], ['View every report, ledger and the audit trail', 1, 1, 1], ['Raise queries on entries', 1, 1, 1], ['Company details, users, lock date, restore', 1, 0, 0]].map(([l, a, b, c]) => `<tr><td>${l}</td>${[a, b, c].map(x => `<td>${x ? '✓' : '—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
    } else {
        body = `<div class="card"><h2>Backup</h2><p class="note" style="margin-bottom:10px">Downloads every company, user and audit log in one file. Bill attachments are included. Keep it safe (for example in Google Drive).</p><button class="btn btn-p" onclick="exportAll()">${ic('dl')} Download full backup</button></div>
            ${isAdmin() ? `<div class="card"><h2>Restore</h2><p class="note" style="margin-bottom:10px">Replaces everything in this browser with the backup.</p><div class="row"><input type="file" id="rsFile" accept=".json"><button class="btn btn-d btn-sm" onclick="importAll()">Restore</button></div></div>
            <div class="card"><h2>Remove this company from this browser</h2><p class="note" style="margin-bottom:10px">Books must be kept for at least 8 years (Companies Act s.128). Download a backup first. Use this only for test or sample companies.</p><button class="btn btn-d btn-sm" onclick="removeCompany()">Remove ${esc(co.profile.name)}</button></div>` : ''}`;
    }
    $('#view').innerHTML = pageHead('Settings', isAdmin() ? '' : 'Only the owner can change settings.') + `<div class="tabs">${tabs.map(([k, l]) => `<a href="#/settings/${k}" class="${tab === k ? 'on' : ''}">${l}</a>`).join('')}</div>` + body;
}
const REMINDER_DEFAULTS = {
    waReminder: 'Dear {customer}, a friendly reminder: {amount} is due against {invoices}. Kindly arrange payment{upi}. – {company}',
    waInvoice: 'Dear {customer}, please find {invoices} for {amount}, due by {due}. – {company}',
    waReceipt: 'Dear {customer}, we have received {amount}. Thank you! – {company}'
};
function fillTemplate(key, vals) {
    const t = co.settings.prefs?.[key] || REMINDER_DEFAULTS[key];
    return t.replace(/\{(\w+)\}/g, (m, k) => vals[k] ?? '');
}
function setProfile(key, value) {
    if (!isAdmin()) return toast('Only the owner can change settings.');
    value = typeof value === 'string' ? value.trim() : value;
    if (['tan', 'respPan'].includes(key)) value = value.toUpperCase();
    if (key === 'tan' && value && !/^[A-Z]{4}\d{5}[A-Z]$/.test(value)) { toast('TAN must look like CHEA12345B.'); return route(); }
    if (key === 'respPan' && value && !panValid(value)) { toast('PAN is not valid.'); return route(); }
    if (key === 'respMobile' && value && !/^[6-9]\d{9}$/.test(value)) { toast('Mobile must be 10 digits.'); return route(); }
    if (key === 'upi' && value && !/^[\w.\-]{2,}@[a-zA-Z]{2,}$/.test(value)) { toast('UPI ID must look like name@bank.'); return route(); }
    if (key === 'aato') value = Number(value) || 0;
    if (key === 'gstFreq' && value === 'quarterly' && (Number(co.profile.aato) || 0) > 50000000) { toast('QRMP is only for turnover up to ₹5 crore.'); return route(); }
    const old = co.profile[key];
    if (old === value) return;
    co.profile[key] = value;
    audit('Setting changed', { entity: 'Settings', ref: key, before: ['logo', 'signature'].includes(key) ? (old ? 'image' : '') : String(old ?? ''), after: ['logo', 'signature'].includes(key) ? (value ? 'new image' : 'removed') : String(value) });
    saveCo(); route(); toast('Saved.');
}
function setPref(key, value) {
    if (!isAdmin()) return toast('Only the owner can change settings.');
    const P = co.settings.prefs ||= {};
    if (typeof value === 'string' && /Days$|largeJv|defaultGst|remindAfter|idleMinutes/.test(key)) value = Number(value) || 0;
    if (key === 'idleMinutes') value = Math.min(240, Math.max(5, value));
    audit('Preference changed', { entity: 'Settings', ref: key, before: String(P[key] ?? ''), after: String(value) });
    P[key] = value; saveCo(); toast('Saved.');
}
function pickImage(key) {
    const input = document.createElement('input');
    input.type = 'file'; input.accept = 'image/*';
    input.onchange = () => {
        const f = input.files[0];
        if (!f || f.size > 2 * 1024 * 1024) return toast('Choose an image under 2 MB.');
        const r = new FileReader();
        r.onload = () => { const img = new Image(); img.onload = () => { const c = document.createElement('canvas'); const k = Math.min(1, 360 / Math.max(img.width, img.height)); c.width = img.width * k; c.height = img.height * k; c.getContext('2d').drawImage(img, 0, 0, c.width, c.height); setProfile(key, c.toDataURL('image/png')); }; img.src = r.result; };
        r.readAsDataURL(f);
    };
    input.click();
}
const IMPORT_COLS = {
    customers: ['Name', 'GSTIN', 'PAN', 'State code', 'City', 'Mobile', 'Email', 'Credit days', 'Opening receivable'],
    vendors: ['Name', 'GSTIN', 'PAN', 'State code', 'City', 'Mobile', 'Email', 'Credit days', 'Opening payable', 'MSME (Y/N)', 'TDS code'],
    items: ['Name', 'Type (goods/service)', 'HSN/SAC', 'GST rate', 'Unit', 'Sale rate', 'Purchase rate', 'Opening qty', 'Opening value']
};
function importTemplate(kind) {
    const ex = { customers: ['Lakshmi Traders', '33AAFFL1234K1Z5', '', '33', 'Chennai', '9840000000', '', '30', '0'], vendors: ['Sri Balaji Suppliers', '', 'ABCPB1234K', '33', 'Madurai', '', '', '30', '0', 'Y', '1027'], items: ['Switch 6A', 'goods', '853650', '18', 'NOS', '45', '30', '100', '3000'] }[kind];
    return toCSV([IMPORT_COLS[kind], ex]);
}
async function runImport(kind) {
    const f = $(`#imp_${kind}`).files[0];
    if (!f) return toast('Choose the CSV file first.');
    const rows = csvParse(await f.text());
    rows.shift();
    let ok = 0;
    const errs = [];
    const codeToKey = c => Object.keys(TDS_SECTIONS).find(k => TDS_SECTIONS[k].code === String(c).trim() || k === String(c).trim()) || '';
    rows.forEach((r, i) => {
        const c = x => (r[x] || '').trim();
        try {
            if (kind === 'items') saveItem({ name: c(0), type: /serv/i.test(c(1)) ? 'service' : 'goods', hsn: c(2), gstRate: Number(c(3)), unit: (c(4) || 'NOS').toUpperCase(), rate: Number(c(5)) || 0, purchaseRate: Number(c(6)) || 0, openQty: Number(c(7)) || 0, openValue: Number(c(8)) || 0, trackStock: !/serv/i.test(c(1)) });
            else {
                const vend = kind === 'vendors';
                saveContact({ type: vend ? 'vendor' : 'customer', name: c(0), gstin: c(1), pan: c(2), state: c(3) || c(1).slice(0, 2) || companyState(), city: c(4), phone: c(5), email: c(6), creditDays: Number(c(7)) || 30, openDr: vend ? 0 : Number(c(8)) || 0, openCr: vend ? Number(c(8)) || 0 : 0, msme: vend && /^y/i.test(c(9)), tdsSection: vend ? codeToKey(c(10)) : '' });
            }
            ok++;
        } catch (e) { errs.push(`Row ${i + 2} (${r[0] || 'blank'}): ${e.message.replace(/\n/g, '; ')}`); }
    });
    audit('Import', { entity: 'Settings', ref: kind, after: `${ok} imported, ${errs.length} skipped` });
    $('#impOut').innerHTML = `<div class="${errs.length ? 'warns' : 'note'}"><b>${ok} ${kind} imported.</b>${errs.length ? `<br>${errs.length} skipped:<br>${errs.slice(0, 30).map(esc).join('<br>')}` : ''}</div>`;
}
function savePrefixes() {
    const before = JSON.stringify(co.settings.prefixes);
    Object.keys(VTYPES).forEach(k => { const v = val('px_' + k).toUpperCase().replace(/[^A-Z0-9-]/g, ''); if (v) co.settings.prefixes[k] = v; });
    audit('Number prefixes changed', { entity: 'Settings', before, after: JSON.stringify(co.settings.prefixes) });
    saveCo(); toast('Saved. New prefixes apply to new vouchers.');
}
async function saveLock() {
    const d = val('lockDate');
    if (d && d > todayISO()) return alert('The lock date cannot be in the future.');
    const reason = await ask({ title: 'Change lock date', message: d ? `Lock all entries up to ${fmtDate(d)}?` : 'Remove the lock?', input: 'Reason', ok: 'Save' });
    if (reason === null) return;
    audit('Lock date changed', { entity: 'Settings', before: co.settings.lockDate || 'none', after: d || 'none', reason });
    co.settings.lockDate = d; saveCo(); route();
}
function userForm(id) {
    const u = id ? meta.users.find(x => x.id === id) : { role: 'accountant', companies: [co.id], active: true };
    modal({
        title: id ? `Edit ${u.name}` : 'Add user',
        body: `<div id="usErr"></div><div class="fg" style="grid-template-columns:1fr 1fr">
            <label class="f">Name<input id="us_name" value="${esc(u.name)}"></label><label class="f">Username<input id="us_user" value="${esc(u.username)}" ${id ? 'readonly' : ''}></label>
            <label class="f">Role<select id="us_role">${Object.entries(ROLES).map(([k, l]) => opt(k, l, u.role)).join('')}</select></label>
            <label class="f">Password ${id ? '<span class="hint">blank = unchanged</span>' : `(${MIN_PASSWORD}+ characters)`}<input id="us_pass" type="password" autocomplete="new-password"></label>
            <label class="f wide">Companies <span class="hint">Hold Ctrl / ⌘ to pick several</span><select id="us_cos" multiple size="4">${opt('all', 'All companies', u.companies === 'all' ? 'all' : '')}${meta.companies.map(c => `<option value="${c.id}" ${u.companies !== 'all' && (u.companies || []).includes(c.id) ? 'selected' : ''}>${esc(c.name)}</option>`).join('')}</select></label>
            <label class="chk"><input type="checkbox" id="us_act" ${u.active !== false ? 'checked' : ''}> Active</label></div>`,
        foot: `<button class="btn btn-s" onclick="closeModal()">Cancel</button><button class="btn btn-p" id="usOk">Save</button>`,
        onOpen: () => $('#usOk').onclick = () => {
            const E = [];
            const name = val('us_name'), user = val('us_user').toLowerCase(), pass = $('#us_pass').value, role = val('us_role');
            const cos = [...$('#us_cos').selectedOptions].map(o => o.value);
            if (!name) E.push('Name is required.');
            if (!/^[a-z0-9._-]{3,30}$/.test(user)) E.push('Username: 3–30 letters or digits.');
            if (!id && meta.users.some(x => x.username === user)) E.push('Username is taken.');
            if (!id && chk('us_act') && limitReached('users')) E.push(`Your ${PLANS[currentPlan()].name} plan allows ${planLimits().users} active user(s). Upgrade in Plan & billing.`);
            if (role === 'auditor' && !hasFeature('auditor')) E.push('The auditor role is in the Professional plan.');
            if ((!id || pass) && pass.length < MIN_PASSWORD) E.push(`Password must be at least ${MIN_PASSWORD} characters.`);
            if (!cos.length) E.push('Choose at least one company.');
            if (id === me.id && (role !== 'admin' || !chk('us_act'))) E.push('You cannot remove your own admin access.');
            if (E.length) { const e = new Error(); e.list = E; return showErr('#usErr', e); }
            const before = id ? `${u.role} · ${u.active !== false ? 'active' : 'disabled'}` : '';
            Object.assign(u, { name, username: user, role, companies: cos.includes('all') ? 'all' : cos, active: chk('us_act') });
            if (pass) { u.salt = randomHex(16); u.hash = hashPassword(pass, u.salt); }
            if (!id) { u.id = uid('u'); u.created = new Date().toISOString(); meta.users.push(u); }
            auditMeta(id ? 'User changed' : 'User added', { entity: 'User', ref: user, before, after: `${ROLES[role]} · ${chk('us_act') ? 'active' : 'disabled'}${pass ? ' · password set' : ''}` });
            closeModal(); route(); toast('User saved.');
        }
    });
}
async function exportAll() {
    const data = { app: 'we-create-erp', version: APP_VERSION, at: new Date().toISOString(), meta, companies: {}, files: {} };
    meta.companies.forEach(c => { data.companies[c.id] = loadCo(c.id); });
    for (const c of Object.values(data.companies)) for (const v of c?.vouchers || []) if (v.attachment) {
        try { const f = await files.get(`att:${v.id}`); if (f) data.files[v.id] = await new Promise(r => { const fr = new FileReader(); fr.onload = () => r(fr.result); fr.readAsDataURL(f); }); } catch (e) { /* skip */ }
    }
    auditMeta('Backup downloaded', { entity: 'System', ref: `${meta.companies.length} companies` });
    download(`we-create-erp-backup-${todayISO()}.json`, JSON.stringify(data), 'application/json');
}
async function importAll() {
    const f = $('#rsFile').files[0];
    if (!f) return toast('Choose the backup file.');
    let data;
    try { data = JSON.parse(await f.text()); } catch (e) { return alert('Not a valid backup file.'); }
    if (data.app !== 'we-create-erp') return alert('This is not a We Create ERP backup.');
    if (!await ask({ title: 'Restore backup', message: `Replace everything in this browser with the backup from ${new Date(data.at).toLocaleString('en-IN')}? You will need to sign in again.`, ok: 'Restore', danger: true })) return;
    Object.keys(localStorage).filter(k => k.startsWith('wcerp.')).forEach(k => localStorage.removeItem(k));
    Object.entries(data.companies).forEach(([id, c]) => c && safeSet(coKey(id), JSON.stringify(c)));
    meta = data.meta;
    auditPush(meta.audit, 'Backup restored', { entity: 'System', ref: data.at });
    saveMeta();
    for (const [vid, url] of Object.entries(data.files || {})) { try { await files.put(`att:${vid}`, await (await fetch(url)).blob()); } catch (e) { /* skip */ } }
    try { sessionStorage.removeItem('wcerp.session'); } catch (e) { /* ignore */ }
    location.reload();
}
async function removeCompany() {
    const name = await ask({ title: 'Remove company', message: `Type the company name to remove "${co.profile.name}" and all its data from this browser.`, input: 'Company name', ok: 'Remove', danger: true });
    if (name === null) return;
    if (name !== co.profile.name) return alert('The name did not match. Nothing was removed.');
    auditMeta('Company removed from this browser', { entity: 'Company', ref: co.profile.name });
    localStorage.removeItem(coKey(co.id));
    meta.companies = meta.companies.filter(c => c.id !== co.id);
    saveMeta(); co = null; go('#/companies');
}
